// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.

import { ServiceChannel } from "lecodes-sdk/plugin"
import type { GeoOptions, GeoPosition, GeolocationEvents, GeolocationParams } from "../contract"

/** What the halves register under. */
export const NAME = "geolocation"
/** The contract's version: the highest `@since` of its members. */
export const VERSION = 1

// ---- the wire, call by call ----------------------------------------------------------------------

/** One fix.
 *  Rejects with "denied" / "unavailable" / "timeout". */
export const getCurrent = (service: ServiceChannel<GeolocationEvents>, options?: GeoOptions): Promise<GeoPosition> =>
  service._call("getCurrent", [options], 1, true)

/** Start the session's watch; resolves once it is live (permission granted, provider started).
 *  A second call while watching resolves at once and keeps the first call's options.
 *  Rejects with "denied" / "unavailable". */
export const startWatch = (service: ServiceChannel<GeolocationEvents>, options?: GeoOptions): Promise<void> =>
  service._call("startWatch", [options], 1, true)

export const stopWatch = (service: ServiceChannel<GeolocationEvents>): Promise<void> =>
  service._call("stopWatch", [], 1, true)

// ---- what the host's half has --------------------------------------------------------------------

/** A method of the contract. */
export type Method = "getCurrent" | "startWatch" | "stopWatch"

/** Whether this host has the service "geolocation" — and, given a method, a half new enough for it
 *  (a method added after the first version of the contract is tagged `@since`). */
export const supports = (method?: Method): boolean =>
  ServiceChannel.supports(NAME)   // every method is of version 1

// ---- the client -----------------------------------------------------------------------------------

/** The service "geolocation" with the wire's methods as its own. */
export class GeolocationBase extends ServiceChannel<GeolocationEvents> {
  constructor(params: GeolocationParams = {}) { super("Geolocation", NAME, params) }

  /** One fix.
   *  Rejects with "denied" / "unavailable" / "timeout". */
  getCurrent(options?: GeoOptions): Promise<GeoPosition> { return getCurrent(this, options) }
  /** Start the session's watch; resolves once it is live (permission granted, provider started).
   *  A second call while watching resolves at once and keeps the first call's options.
   *  Rejects with "denied" / "unavailable". */
  startWatch(options?: GeoOptions): Promise<void> { return startWatch(this, options) }
  stopWatch(): Promise<void> { return stopWatch(this) }
}
