// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.

import Foundation
import LeCodes

// MARK: - The contract's types

public struct GeolocationParams {
    public init() {}

    init?(wire: Any?) {
        guard wire == nil || wire is NSNull || Wire.object(wire) != nil else { return nil }
    }
}

public struct GeoOptions {
    /// Prefer the precise (GPS) provider — slower first fix, more battery. Default false.
    public var highAccuracy: Bool?
    /// getCurrent only: reject with "timeout" when no fix arrives in this many ms.
    public var timeout: Double?

    public init(highAccuracy: Bool? = nil, timeout: Double? = nil) {
        self.highAccuracy = highAccuracy
        self.timeout = timeout
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["highAccuracy"]) {
            guard let highAccuracy = Wire.bool(o["highAccuracy"]) else { return nil }
            self.highAccuracy = highAccuracy
        } else { self.highAccuracy = nil }
        if Wire.present(o["timeout"]) {
            guard let timeout = Wire.f64(o["timeout"]) else { return nil }
            self.timeout = timeout
        } else { self.timeout = nil }
    }
}

public struct GeoPosition {
    public var latitude: Double
    public var longitude: Double
    /// Horizontal accuracy radius, meters.
    public var accuracy: Double
    /// Meters above sea level; null when the provider does not know.
    public var altitude: Double?
    /// Direction of travel, degrees clockwise from north; null when stationary or unknown.
    public var heading: Double?
    /// Ground speed, m/s; null when unknown.
    public var speed: Double?
    /// When the fix was taken, ms since the epoch.
    public var timestamp: Double

    public init(latitude: Double, longitude: Double, accuracy: Double, altitude: Double? = nil, heading: Double? = nil, speed: Double? = nil, timestamp: Double) {
        self.latitude = latitude
        self.longitude = longitude
        self.accuracy = accuracy
        self.altitude = altitude
        self.heading = heading
        self.speed = speed
        self.timestamp = timestamp
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["latitude"] = latitude
        o["longitude"] = longitude
        o["accuracy"] = accuracy
        if let v = altitude { o["altitude"] = v } else { o["altitude"] = NSNull() }
        if let v = heading { o["heading"] = v } else { o["heading"] = NSNull() }
        if let v = speed { o["speed"] = v } else { o["speed"] = NSNull() }
        o["timestamp"] = timestamp
        return o
    }
}

// MARK: - Geolocation

/// The codes the calls of "geolocation" reject with.
public enum GeolocationCode: String, PluginCode {
    case denied
    case unavailable
    case timeout
}

/// The events of "geolocation": what the plugin sends the app. Any thread.
public struct GeolocationEvents {
    let channel: ServiceChannel

    /// A fix of the live watch.
    public func position(_ payload: GeoPosition) { channel.emit("position", payload.wire) }
}

/// The service "geolocation".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol GeolocationPlugin: AnyObject {
    /// One fix.
    /// Rejects with .denied / .unavailable / .timeout.
    func getCurrent(_ options: GeoOptions?, _ reply: Reply<GeoPosition, GeolocationCode>)
    /// Start the session's watch; resolves once it is live (permission granted, provider started).
    /// A second call while watching resolves at once and keeps the first call's options.
    /// Rejects with .denied / .unavailable.
    func startWatch(_ options: GeoOptions?, _ reply: Reply<Void, GeolocationCode>)
    func stopWatch(_ reply: Reply<Void, GeolocationCode>)

    /// The session closed (the app's close, the world's teardown): stop what it started.
    func close()
}

public extension GeolocationPlugin {
    func close() {}
}

public enum GeolocationChannel {
    /// What the halves register under.
    public static let name = "geolocation"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the service: `make` builds one session from its params. It must be cheap — no prompt,
    /// no I/O: that belongs to the first call that needs it.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (GeolocationParams, GeolocationEvents) -> GeolocationPlugin) {
        engine.registerService(name) { params, channel in
            GeolocationGlue(make(GeolocationParams(wire: params) ?? GeolocationParams(), GeolocationEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class GeolocationGlue: ServiceInstance {
    private let plugin: GeolocationPlugin

    init(_ plugin: GeolocationPlugin) { self.plugin = plugin }

    func call(_ method: String, _ args: [Any], _ settle: ChannelSettle) {
        switch method {
        case "getCurrent":
            let a0: Any? = args.count > 0 ? args[0] : nil
            var options: GeoOptions? = nil
            if Wire.present(a0) {
                guard let v = GeoOptions(wire: a0) else { return settle.reject("bad arguments — Geolocation.getCurrent: options") }
                options = v
            }
            plugin.getCurrent(options, Reply<GeoPosition, GeolocationCode>(settle) { v in v.wire })
        case "startWatch":
            let a0: Any? = args.count > 0 ? args[0] : nil
            var options: GeoOptions? = nil
            if Wire.present(a0) {
                guard let v = GeoOptions(wire: a0) else { return settle.reject("bad arguments — Geolocation.startWatch: options") }
                options = v
            }
            plugin.startWatch(options, Reply<Void, GeolocationCode>(settle) { _ in nil })
        case "stopWatch":
            plugin.stopWatch(Reply<Void, GeolocationCode>(settle) { _ in nil })
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func close() { plugin.close() }
}
