// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.

import Foundation
import LeCodes

// MARK: - The contract's types

public struct GeolocationParams {
    public init() {}

    init?(wire: WireIn) {
        guard !wire.isPresent || wire.isObject else { return nil }
    }
}

public struct GeoOptions {
    /// Prefer the precise (GPS) provider — slower first fix, more battery. Default false.
    public var highAccuracy: Bool?
    /// getCurrent only: reject with "timeout" when no fix arrives in this many ms.
    public var timeout: Double?

    public init(highAccuracy: Bool? = nil, timeout: Double? = nil) {
        self.highAccuracy = highAccuracy
        self.timeout = timeout
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["highAccuracy", 0]
        if m0.isPresent {
            guard let v = m0.bool else { return nil }
            self.highAccuracy = v
        } else {
            self.highAccuracy = nil
        }
        let m1 = wire["timeout", 1]
        if m1.isPresent {
            guard let v = m1.f64 else { return nil }
            self.timeout = v
        } else {
            self.timeout = nil
        }
    }
}

public struct GeoPosition {
    public var latitude: Double
    public var longitude: Double
    /// Horizontal accuracy radius, meters.
    public var accuracy: Double
    /// Meters above sea level; null when the provider does not know.
    public var altitude: Double?
    /// Direction of travel, degrees clockwise from north; null when stationary or unknown.
    public var heading: Double?
    /// Ground speed, m/s; null when unknown.
    public var speed: Double?
    /// When the fix was taken, ms since the epoch.
    public var timestamp: Double

    public init(latitude: Double, longitude: Double, accuracy: Double, altitude: Double? = nil, heading: Double? = nil, speed: Double? = nil, timestamp: Double) {
        self.latitude = latitude
        self.longitude = longitude
        self.accuracy = accuracy
        self.altitude = altitude
        self.heading = heading
        self.speed = speed
        self.timestamp = timestamp
    }

    func write(to w: WireOut) {
        w.beginObject(7)
        w.key("latitude"); w.f64(self.latitude)
        w.key("longitude"); w.f64(self.longitude)
        w.key("accuracy"); w.f64(self.accuracy)
        w.key("altitude")
        if let v0 = self.altitude { w.f64(v0) } else { w.null() }
        w.key("heading")
        if let v0 = self.heading { w.f64(v0) } else { w.null() }
        w.key("speed")
        if let v0 = self.speed { w.f64(v0) } else { w.null() }
        w.key("timestamp"); w.f64(self.timestamp)
        w.end()
    }
}

// MARK: - Geolocation

/// The codes the calls of "geolocation" reject with.
public enum GeolocationCode: String, PluginCode {
    case denied
    case unavailable
    case timeout
}

/// The events of "geolocation": what the plugin sends the app. Any thread.
public struct GeolocationEvents {
    let channel: ServiceChannel

    /// A fix of the live watch.
    public func position(_ payload: GeoPosition) {
        channel.emit("position") { w in payload.write(to: w) }
    }
}

/// The service "geolocation".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol GeolocationPlugin: AnyObject {
    /// One fix.
    /// Rejects with .denied / .unavailable / .timeout.
    func getCurrent(_ options: GeoOptions?, _ reply: Reply<GeoPosition, GeolocationCode>)
    /// Start the session's watch; resolves once it is live (permission granted, provider started).
    /// A second call while watching resolves at once and keeps the first call's options.
    /// Rejects with .denied / .unavailable.
    func startWatch(_ options: GeoOptions?, _ reply: Reply<Void, GeolocationCode>)
    func stopWatch(_ reply: Reply<Void, GeolocationCode>)

    /// The session closed (the app's close, the world's teardown): stop what it started.
    func close()
}

public extension GeolocationPlugin {
    func close() {}
}

public enum GeolocationChannel {
    /// What the halves register under.
    public static let name = "geolocation"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the service: `make` builds one session from its params. It must be cheap — no prompt,
    /// no I/O: that belongs to the first call that needs it.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (GeolocationParams, GeolocationEvents) -> GeolocationPlugin) {
        engine.registerService(name, version: Int32(version)) { params, channel in
            GeolocationGlue(make(WireIn.of(params, { GeolocationParams(wire: $0) }) ?? GeolocationParams(), GeolocationEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class GeolocationGlue: WireServiceInstance {
    private let plugin: GeolocationPlugin

    init(_ plugin: GeolocationPlugin) { self.plugin = plugin }

    func call(_ method: String, wire args: WireIn, _ settle: ChannelSettle) {
        switch method {
        case "getCurrent":
            let w0 = args[0]
            var a0: GeoOptions? = nil
            if w0.isPresent {
                guard let v = GeoOptions(wire: w0) else { return settle.reject("bad arguments — Geolocation.getCurrent: options") }
                a0 = v
            }
            plugin.getCurrent(a0, Reply<GeoPosition, GeolocationCode>(settle) { v, w in v.write(to: w) })
        case "startWatch":
            let w0 = args[0]
            var a0: GeoOptions? = nil
            if w0.isPresent {
                guard let v = GeoOptions(wire: w0) else { return settle.reject("bad arguments — Geolocation.startWatch: options") }
                a0 = v
            }
            plugin.startWatch(a0, Reply<Void, GeolocationCode>(settle))
        case "stopWatch":
            plugin.stopWatch(Reply<Void, GeolocationCode>(settle))
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func close() { plugin.close() }
}
