// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// push: the service "push", contract version 1.

package io.letary.lecodes.plugins.push

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Services
import io.letary.lecodes.services.Wire
import org.json.JSONArray
import org.json.JSONObject

// ---- The contract's types ----

class PushParams {
    companion object {
        internal fun fromWire(wire: Any?): PushParams? = if (!Wire.present(wire) || Wire.obj(wire) != null) PushParams() else null
    }
}

enum class PushStatusPermission(val wire: String) {
    GRANTED("granted"),
    DENIED("denied"),
    PROMPT("prompt");
}

data class PushStatus(
    /** The OS permission of the host app. "prompt" = not asked yet. */
    val permission: PushStatusPermission,
    /** Whether this device holds a registration (an address) for this app. */
    val registered: Boolean,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("permission", permission.wire)
            o.put("registered", registered)
            return o
        }
}

data class PushRegisterOptions(
    /**
     * The app's OWN user id. Client-asserted and unverified. The registration reflects the latest
     * call: registering without it clears it.
     */
    val user: String? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): PushRegisterOptions? {
            val o = Wire.obj(wire) ?: return null
            val user = if (Wire.present(o.opt("user"))) (Wire.string(o.opt("user")) ?: return null) else null
            return PushRegisterOptions(user = user)
        }
    }
}

data class PushRegistration(
    val address: String,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("address", address)
            return o
        }
}

/** A delivered notification, as the app sees it. */
data class PushPayload(
    val title: String,
    val body: String? = null,
    /** A deep link — it also rides the app's own link path (`app.launchUrl`, the "url" event). */
    val url: String? = null,
    /** The developer's own JSON object, ≤ 2 KB serialized. */
    val data: Map<String, Any>? = null,
    val badge: Int? = null,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("title", title)
            body?.let { v -> o.put("body", v) }
            url?.let { v -> o.put("url", v) }
            data?.let { v -> o.put("data", Wire.writeMap(v) { v1 -> v1 }) }
            badge?.let { v -> o.put("badge", v) }
            return o
        }
}

// ---- Push ----

/** The codes the calls of "push" reject with. */
enum class PushCode(override val code: String) : PluginCode {
    DENIED("denied"),
    UNAVAILABLE("unavailable"),
}

/** The events of "push": what the plugin sends the app. Any thread. */
class PushEvents(private val channel: PluginEmit) {
    /** Arrived while this app was in the foreground (the host shows no banner). */
    fun message(payload: PushPayload) = channel.emit("message", payload.wire)

    /** Tapped while the world was alive. */
    fun tap(payload: PushPayload) = channel.emit("tap", payload.wire)
}

/**
 * The service "push".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface PushPlugin {
    /** Permission + registration state. Never prompts. */
    fun getStatus(reply: Reply<PushStatus, PushCode>)

    /**
     * Ask for the permission (the first time) and register this device. Idempotent.
     * Rejects with DENIED / UNAVAILABLE.
     */
    fun register(options: PushRegisterOptions?, reply: Reply<PushRegistration, PushCode>)

    /**
     * Remove this device's registration.
     * Rejects with UNAVAILABLE.
     */
    fun unregister(reply: Reply<Unit, PushCode>)

    /** The notification that cold-started this world, or null. Stable across calls. */
    fun getLaunch(reply: Reply<PushPayload?, PushCode>)

    /** The session closed (the app's close, the world's teardown): stop what it started. */
    fun close() {}
}

object PushChannel {
    /** What the halves register under. */
    const val NAME = "push"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the service: `make` builds one session from its params. It must be cheap — no
     *  prompt, no I/O: that belongs to the first call that needs it. */
    fun register(engine: LecodesEngine, make: (params: PushParams, events: PushEvents) -> PushPlugin) {
        engine.registerService(NAME, VERSION) { params, channel ->
            val plugin = make(PushParams.fromWire(params) ?: PushParams(), PushEvents { event, data -> channel.emitValue(event, data) })
            Services.Instance(onCall = { call -> PushGlue.call(plugin, call.method, call.args, call) }, onClose = { plugin.close() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object PushGlue {
    fun call(plugin: PushPlugin, method: String, args: JSONArray, settle: ChannelSettle) {
        when (method) {
            "getStatus" -> {
                plugin.getStatus(Reply<PushStatus, PushCode>(settle) { v -> v.wire })
            }
            "register" -> {
                val a0 = args.opt(0)
                val options = if (Wire.present(a0)) (PushRegisterOptions.fromWire(a0) ?: return settle.reject("bad arguments — Push.register: options")) else null
                plugin.register(options, Reply<PushRegistration, PushCode>(settle) { v -> v.wire })
            }
            "unregister" -> {
                plugin.unregister(Reply<Unit, PushCode>(settle) { null })
            }
            "getLaunch" -> {
                plugin.getLaunch(Reply<PushPayload?, PushCode>(settle) { v -> v?.wire })
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
