// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// push: the service "push", contract version 1.

package io.letary.lecodes.plugins.push

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Services
import io.letary.lecodes.services.Wire
import io.letary.lecodes.core.PackedReader
import io.letary.lecodes.core.PackedWriter

// ---- The contract's types ----

class PushParams {
    companion object {
        internal fun read(r: PackedReader): PushParams? {
            if (r.isNull()) return PushParams()
            if (r.beginObject() < 0) return null
            return PushParams()
        }
    }
}

enum class PushStatusPermission(val wire: String) {
    GRANTED("granted"),
    DENIED("denied"),
    PROMPT("prompt");
}

data class PushStatus(
    /** The OS permission of the host app. "prompt" = not asked yet. */
    val permission: PushStatusPermission,
    /** Whether this device holds a registration (an address) for this app. */
    val registered: Boolean,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("permission"); w.string(this.permission.wire)
        w.key("registered"); w.bool(this.registered)
        w.end()
    }
}

data class PushRegisterOptions(
    /**
     * The app's OWN user id. Client-asserted and unverified. The registration reflects the latest
     * call: registering without it clears it.
     */
    val user: String? = null,
) {
    companion object {
        internal fun read(r: PackedReader): PushRegisterOptions? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: String? = null
            repeat(n) {
                when (r.key()) {
                    "user" -> if (r.isNull()) r.skip() else m0 = r.string() ?: return null
                    else -> r.skip()
                }
            }
            return PushRegisterOptions(user = m0)
        }
    }
}

data class PushRegistration(
    val address: String,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("address"); w.string(this.address)
        w.end()
    }
}

/** A delivered notification, as the app sees it. */
data class PushPayload(
    val title: String,
    val body: String? = null,
    /** A deep link — it also rides the app's own link path (`app.launchUrl`, the "url" event). */
    val url: String? = null,
    /** The developer's own JSON object, ≤ 2 KB serialized. */
    val data: Map<String, Any>? = null,
    val badge: Int? = null,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("title"); w.string(this.title)
        this.body?.let { v -> w.key("body"); w.string(v) }
        this.url?.let { v -> w.key("url"); w.string(v) }
        this.data?.let { v ->
            w.key("data")
            w.beginObject()
            for ((k1, v1) in v) {
                w.key(k1)
                w.json(v1)
            }
            w.end()
        }
        this.badge?.let { v -> w.key("badge"); w.i32(v) }
        w.end()
    }
}

// ---- Push ----

/** The codes the calls of "push" reject with. */
enum class PushCode(override val code: String) : PluginCode {
    DENIED("denied"),
    UNAVAILABLE("unavailable"),
}

/** The events of "push": what the plugin sends the app. Any thread. */
class PushEvents(private val channel: PluginEmit) {
    /** Arrived while this app was in the foreground (the host shows no banner). */
    fun message(payload: PushPayload) {
        val w = PackedWriter()
        payload.write(w)
        channel.emit("message", w.bytes())
    }

    /** Tapped while the world was alive. */
    fun tap(payload: PushPayload) {
        val w = PackedWriter()
        payload.write(w)
        channel.emit("tap", w.bytes())
    }
}

/**
 * The service "push".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface PushPlugin {
    /** Permission + registration state. Never prompts. */
    fun getStatus(reply: Reply<PushStatus, PushCode>)

    /**
     * Ask for the permission (the first time) and register this device. Idempotent.
     * Rejects with DENIED / UNAVAILABLE.
     */
    fun register(options: PushRegisterOptions?, reply: Reply<PushRegistration, PushCode>)

    /**
     * Remove this device's registration.
     * Rejects with UNAVAILABLE.
     */
    fun unregister(reply: Reply<Unit, PushCode>)

    /** The notification that cold-started this world, or null. Stable across calls. */
    fun getLaunch(reply: Reply<PushPayload?, PushCode>)

    /** The session closed (the app's close, the world's teardown): stop what it started. */
    fun close() {}
}

object PushChannel {
    /** What the halves register under. */
    const val NAME = "push"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the service: `make` builds one session from its params. It must be cheap — no
     *  prompt, no I/O: that belongs to the first call that needs it. */
    fun register(engine: LecodesEngine, make: (params: PushParams, events: PushEvents) -> PushPlugin) {
        engine.registerService(NAME, VERSION) { params, channel ->
            val plugin = make(PushParams.read(Wire.reader(params)) ?: PushParams(), PushEvents { event, packed -> channel.emitPacked(event, packed) })
            Services.Instance(onCall = { call -> PushGlue.call(plugin, call.method, call.reader(), call) }, onClose = { plugin.close() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object PushGlue {
    fun call(plugin: PushPlugin, method: String, r: PackedReader, settle: ChannelSettle) {
        val n = r.beginArray()   // the arguments, in their order
        when (method) {
            "getStatus" -> {
                plugin.getStatus(Reply<PushStatus, PushCode>(settle) { v, w -> v.write(w) })
            }
            "register" -> {
                val a0 = if (0 < n && !r.isNull()) (PushRegisterOptions.read(r) ?: return settle.reject("bad arguments — Push.register: options")) else { if (0 < n) r.skip(); null }
                plugin.register(a0, Reply<PushRegistration, PushCode>(settle) { v, w -> v.write(w) })
            }
            "unregister" -> {
                plugin.unregister(Reply<Unit, PushCode>(settle, null))
            }
            "getLaunch" -> {
                plugin.getLaunch(Reply<PushPayload?, PushCode>(settle) { v, w -> if (v != null) { v.write(w) } })
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
