// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.

package io.letary.lecodes.plugins.map

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.NativeViews
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Wire
import org.json.JSONArray
import org.json.JSONObject

// ---- The contract's types ----

data class MapParams(
    /** A style URL the map fetches itself. */
    val style: String? = null,
    /**
     * A style as JSON text; wins over `style`. It has no base url: every url INSIDE it (sources,
     * sprite, glyphs) must be absolute.
     */
    val styleJson: String? = null,
    val center: Pair<Double, Double>? = null,
    /** Default 12 with a center. */
    val zoom: Double? = null,
    val minZoom: Double? = null,
    val maxZoom: Double? = null,
    /** Degrees clockwise from north. */
    val bearing: Double? = null,
    /** Degrees from the vertical. */
    val pitch: Double? = null,
    /** The two-finger rotate gesture. Default true. */
    val rotate: Boolean? = null,
    /** The two-finger tilt gesture. Default false. */
    val tilt: Boolean? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapParams? {
            val o = Wire.obj(wire) ?: return null
            val style = if (Wire.present(o.opt("style"))) (Wire.string(o.opt("style")) ?: return null) else null
            val styleJson = if (Wire.present(o.opt("styleJson"))) (Wire.string(o.opt("styleJson")) ?: return null) else null
            val center = if (Wire.present(o.opt("center"))) (Wire.array(o.opt("center"), 2)?.let { v0 -> val v0_0 = Wire.f64(v0.opt(0)) ?: return@let null; val v0_1 = Wire.f64(v0.opt(1)) ?: return@let null; Pair(v0_0, v0_1) } ?: return null) else null
            val zoom = if (Wire.present(o.opt("zoom"))) (Wire.f64(o.opt("zoom")) ?: return null) else null
            val minZoom = if (Wire.present(o.opt("minZoom"))) (Wire.f64(o.opt("minZoom")) ?: return null) else null
            val maxZoom = if (Wire.present(o.opt("maxZoom"))) (Wire.f64(o.opt("maxZoom")) ?: return null) else null
            val bearing = if (Wire.present(o.opt("bearing"))) (Wire.f64(o.opt("bearing")) ?: return null) else null
            val pitch = if (Wire.present(o.opt("pitch"))) (Wire.f64(o.opt("pitch")) ?: return null) else null
            val rotate = if (Wire.present(o.opt("rotate"))) (Wire.bool(o.opt("rotate")) ?: return null) else null
            val tilt = if (Wire.present(o.opt("tilt"))) (Wire.bool(o.opt("tilt")) ?: return null) else null
            return MapParams(style = style, styleJson = styleJson, center = center, zoom = zoom, minZoom = minZoom, maxZoom = maxZoom, bearing = bearing, pitch = pitch, rotate = rotate, tilt = tilt)
        }
    }
}

enum class MapLayerKind(val wire: String) {
    MARKERS("markers"),
    LINE("line");

    companion object {
        internal fun fromWire(wire: Any?): MapLayerKind? = values().firstOrNull { it.wire == wire }
    }
}

/** The keys of both kinds; a half reads the ones of the kind it is asked for. */
data class MapLayerOptions(
    /** markers: group nearby markers (a cluster tap zooms in). Default false. */
    val cluster: Boolean? = null,
    /** markers: px. Default 50. */
    val clusterRadius: Double? = null,
    /** markers: the zoom at which clusters stop forming. */
    val clusterMaxZoom: Double? = null,
    /** line. */
    val color: String? = null,
    /** line: px. Default 4. */
    val width: Double? = null,
    /** line: 0–1. Default 1. */
    val opacity: Double? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapLayerOptions? {
            val o = Wire.obj(wire) ?: return null
            val cluster = if (Wire.present(o.opt("cluster"))) (Wire.bool(o.opt("cluster")) ?: return null) else null
            val clusterRadius = if (Wire.present(o.opt("clusterRadius"))) (Wire.f64(o.opt("clusterRadius")) ?: return null) else null
            val clusterMaxZoom = if (Wire.present(o.opt("clusterMaxZoom"))) (Wire.f64(o.opt("clusterMaxZoom")) ?: return null) else null
            val color = if (Wire.present(o.opt("color"))) (Wire.string(o.opt("color")) ?: return null) else null
            val width = if (Wire.present(o.opt("width"))) (Wire.f64(o.opt("width")) ?: return null) else null
            val opacity = if (Wire.present(o.opt("opacity"))) (Wire.f64(o.opt("opacity")) ?: return null) else null
            return MapLayerOptions(cluster = cluster, clusterRadius = clusterRadius, clusterMaxZoom = clusterMaxZoom, color = color, width = width, opacity = opacity)
        }
    }
}

data class MapCameraMove(
    val zoom: Double? = null,
    val bearing: Double? = null,
    val pitch: Double? = null,
    /** flyTo only: ms. Default 600. */
    val duration: Double? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapCameraMove? {
            val o = Wire.obj(wire) ?: return null
            val zoom = if (Wire.present(o.opt("zoom"))) (Wire.f64(o.opt("zoom")) ?: return null) else null
            val bearing = if (Wire.present(o.opt("bearing"))) (Wire.f64(o.opt("bearing")) ?: return null) else null
            val pitch = if (Wire.present(o.opt("pitch"))) (Wire.f64(o.opt("pitch")) ?: return null) else null
            val duration = if (Wire.present(o.opt("duration"))) (Wire.f64(o.opt("duration")) ?: return null) else null
            return MapCameraMove(zoom = zoom, bearing = bearing, pitch = pitch, duration = duration)
        }
    }
}

/** Px, or a share of the view's size as "NN%". */
sealed class MapInset {
    data class OfNumber(val value: Double) : MapInset()
    data class OfString(val value: String) : MapInset()

    companion object {
        internal fun fromWire(wire: Any?): MapInset? {
            Wire.f64(wire)?.let { return OfNumber(it) }
            Wire.string(wire)?.let { return OfString(it) }
            return null
        }
    }
}

data class MapPadding(
    val top: MapInset? = null,
    val left: MapInset? = null,
    val bottom: MapInset? = null,
    val right: MapInset? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapPadding? {
            val o = Wire.obj(wire) ?: return null
            val top = if (Wire.present(o.opt("top"))) (MapInset.fromWire(o.opt("top")) ?: return null) else null
            val left = if (Wire.present(o.opt("left"))) (MapInset.fromWire(o.opt("left")) ?: return null) else null
            val bottom = if (Wire.present(o.opt("bottom"))) (MapInset.fromWire(o.opt("bottom")) ?: return null) else null
            val right = if (Wire.present(o.opt("right"))) (MapInset.fromWire(o.opt("right")) ?: return null) else null
            return MapPadding(top = top, left = left, bottom = bottom, right = right)
        }
    }
}

sealed class MapFitOptionsPadding {
    data class OfNumber(val value: Double) : MapFitOptionsPadding()
    data class OfMapPadding(val value: MapPadding) : MapFitOptionsPadding()

    companion object {
        internal fun fromWire(wire: Any?): MapFitOptionsPadding? {
            Wire.f64(wire)?.let { return OfNumber(it) }
            MapPadding.fromWire(wire)?.let { return OfMapPadding(it) }
            return null
        }
    }
}

data class MapFitOptions(
    /** Around the points: px on every edge, or per edge. Added to the view padding. */
    val padding: MapFitOptionsPadding? = null,
    /** Default: 16 for one point, none otherwise. */
    val maxZoom: Double? = null,
    /** Default true. */
    val animate: Boolean? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapFitOptions? {
            val o = Wire.obj(wire) ?: return null
            val padding = if (Wire.present(o.opt("padding"))) (MapFitOptionsPadding.fromWire(o.opt("padding")) ?: return null) else null
            val maxZoom = if (Wire.present(o.opt("maxZoom"))) (Wire.f64(o.opt("maxZoom")) ?: return null) else null
            val animate = if (Wire.present(o.opt("animate"))) (Wire.bool(o.opt("animate")) ?: return null) else null
            return MapFitOptions(padding = padding, maxZoom = maxZoom, animate = animate)
        }
    }
}

data class MapCamera(
    val center: Pair<Double, Double>,
    val zoom: Double,
    val bearing: Double,
    val pitch: Double,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("center", JSONArray().put(Wire.number(center.first)).put(Wire.number(center.second)))
            o.put("zoom", Wire.number(zoom))
            o.put("bearing", Wire.number(bearing))
            o.put("pitch", Wire.number(pitch))
            return o
        }
}

data class MapUserLocationOptions(
    /** Meters — the halo around the dot. */
    val accuracy: Double? = null,
    /** Degrees clockwise from north — the direction wedge; null hides it. */
    val heading: Double? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): MapUserLocationOptions? {
            val o = Wire.obj(wire) ?: return null
            val accuracy = if (Wire.present(o.opt("accuracy"))) (Wire.f64(o.opt("accuracy")) ?: return null) else null
            val heading = if (Wire.present(o.opt("heading"))) (Wire.f64(o.opt("heading")) ?: return null) else null
            return MapUserLocationOptions(accuracy = accuracy, heading = heading)
        }
    }
}

sealed class MapFeatureId {
    data class OfString(val value: String) : MapFeatureId()
    data class OfNumber(val value: Double) : MapFeatureId()

    internal val wire: Any
        get() = when (this) {
            is OfString -> value
            is OfNumber -> Wire.number(value)
        }
}

/** A feature of a managed source under a tap. */
data class MapFeature(
    /** The source's name — the layer's name in the app. */
    val source: String,
    val id: MapFeatureId? = null,
    val properties: Map<String, Any>,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("source", source)
            o.put("id", (id?.wire ?: JSONObject.NULL))
            o.put("properties", Wire.writeMap(properties) { v0 -> v0 })
            return o
        }
}

data class MapTap(
    val lngLat: Pair<Double, Double>,
    /** View-space point, logical px. */
    val point: Pair<Double, Double>,
    /**
     * Absent for a tap that hit no feature of a managed source. A tap on a CLUSTER zooms in and
     * sends no event.
     */
    val feature: MapFeature? = null,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("lngLat", JSONArray().put(Wire.number(lngLat.first)).put(Wire.number(lngLat.second)))
            o.put("point", JSONArray().put(Wire.number(point.first)).put(Wire.number(point.second)))
            feature?.let { v -> o.put("feature", v.wire) }
            return o
        }
}

// ---- MapView ----

/** The codes the calls of "map" reject with. */
enum class MapViewCode(override val code: String) : PluginCode {
    NOT_READY("notReady"),
    NO_POINTS("noPoints"),
}

/** The events of "map": what the plugin sends the app. From the main thread. */
class MapViewEvents(private val channel: PluginEmit) {
    /** The style loaded and the map takes calls. Fires again after every style reload. */
    fun ready() = channel.emit("ready", null)

    fun tap(payload: MapTap) = channel.emit("tap", payload.wire)

    /** The camera settled after a gesture or an animation. */
    fun moveEnd(payload: MapCamera) = channel.emit("moveEnd", payload.wire)

    /** A problem that is never fatal: a style that would not load, a source out of reach. */
    fun error(message: String) {
        val o = JSONObject()
        o.put("message", message)
        channel.emit("error", o)
    }
}

/**
 * The view "map".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface MapViewPlugin {
    /** The view the host mounts: fullscreen, or embedded among a screen's children. */
    val view: android.view.View

    /**
     * Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
     * layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
     * Rejects with NOT_READY.
     */
    fun ensureLayer(source: String, kind: MapLayerKind, options: MapLayerOptions?, reply: Reply<Unit, MapViewCode>)

    fun removeLayer(source: String, reply: Reply<Unit, MapViewCode>)

    /**
     * Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
     * Rejects with NOT_READY.
     */
    fun setData(source: String, geojson: Any, reply: Reply<Unit, MapViewCode>)

    fun flyTo(center: Pair<Double, Double>, options: MapCameraMove?, reply: Reply<Unit, MapViewCode>)

    fun jumpTo(center: Pair<Double, Double>, options: MapCameraMove?, reply: Reply<Unit, MapViewCode>)

    /**
     * Fit the camera to the points.
     * Rejects with NO_POINTS.
     */
    fun fitPoints(points: List<Pair<Double, Double>>, options: MapFitOptions?, reply: Reply<Unit, MapViewCode>)

    /** The part of the view covered by the app's UI; camera moves center inside the rest. */
    fun setPadding(padding: MapPadding, reply: Reply<Unit, MapViewCode>)

    /** Rejects with NOT_READY. */
    fun getCamera(reply: Reply<MapCamera, MapViewCode>)

    /** Move the user puck; null hides it. */
    fun setUserLocation(lngLat: Pair<Double, Double>?, options: MapUserLocationOptions?, reply: Reply<Unit, MapViewCode>)

    /** The instance goes (the world swapped): release the hardware. */
    fun destroy() {}
}

object MapViewChannel {
    /** What the halves register under. */
    const val NAME = "map"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the view: `make` builds one instance from its params. */
    fun register(engine: LecodesEngine, make: (params: MapParams, events: MapViewEvents) -> MapViewPlugin) {
        engine.registerView(NAME, VERSION) { params, channel ->
            val plugin = make(MapParams.fromWire(params) ?: MapParams(), MapViewEvents { event, data -> channel.emitValue(event, data) })
            NativeViews.Instance(plugin.view, onCall = { call -> MapViewGlue.call(plugin, call.method, call.args, call) }, onDestroy = { plugin.destroy() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object MapViewGlue {
    fun call(plugin: MapViewPlugin, method: String, args: JSONArray, settle: ChannelSettle) {
        when (method) {
            "ensureLayer" -> {
                val source = Wire.string(args.opt(0)) ?: return settle.reject("bad arguments — MapView.ensureLayer: source")
                val kind = MapLayerKind.fromWire(args.opt(1)) ?: return settle.reject("bad arguments — MapView.ensureLayer: kind")
                val a2 = args.opt(2)
                val options = if (Wire.present(a2)) (MapLayerOptions.fromWire(a2) ?: return settle.reject("bad arguments — MapView.ensureLayer: options")) else null
                plugin.ensureLayer(source, kind, options, Reply<Unit, MapViewCode>(settle) { null })
            }
            "removeLayer" -> {
                val source = Wire.string(args.opt(0)) ?: return settle.reject("bad arguments — MapView.removeLayer: source")
                plugin.removeLayer(source, Reply<Unit, MapViewCode>(settle) { null })
            }
            "setData" -> {
                val source = Wire.string(args.opt(0)) ?: return settle.reject("bad arguments — MapView.setData: source")
                val geojson = Wire.json(args.opt(1)) ?: return settle.reject("bad arguments — MapView.setData: geojson")
                plugin.setData(source, geojson, Reply<Unit, MapViewCode>(settle) { null })
            }
            "flyTo" -> {
                val center = Wire.array(args.opt(0), 2)?.let { v0 -> val v0_0 = Wire.f64(v0.opt(0)) ?: return@let null; val v0_1 = Wire.f64(v0.opt(1)) ?: return@let null; Pair(v0_0, v0_1) } ?: return settle.reject("bad arguments — MapView.flyTo: center")
                val a1 = args.opt(1)
                val options = if (Wire.present(a1)) (MapCameraMove.fromWire(a1) ?: return settle.reject("bad arguments — MapView.flyTo: options")) else null
                plugin.flyTo(center, options, Reply<Unit, MapViewCode>(settle) { null })
            }
            "jumpTo" -> {
                val center = Wire.array(args.opt(0), 2)?.let { v0 -> val v0_0 = Wire.f64(v0.opt(0)) ?: return@let null; val v0_1 = Wire.f64(v0.opt(1)) ?: return@let null; Pair(v0_0, v0_1) } ?: return settle.reject("bad arguments — MapView.jumpTo: center")
                val a1 = args.opt(1)
                val options = if (Wire.present(a1)) (MapCameraMove.fromWire(a1) ?: return settle.reject("bad arguments — MapView.jumpTo: options")) else null
                plugin.jumpTo(center, options, Reply<Unit, MapViewCode>(settle) { null })
            }
            "fitPoints" -> {
                val points = Wire.list(args.opt(0)) { v0 -> Wire.array(v0, 2)?.let { v1 -> val v1_0 = Wire.f64(v1.opt(0)) ?: return@let null; val v1_1 = Wire.f64(v1.opt(1)) ?: return@let null; Pair(v1_0, v1_1) } } ?: return settle.reject("bad arguments — MapView.fitPoints: points")
                val a1 = args.opt(1)
                val options = if (Wire.present(a1)) (MapFitOptions.fromWire(a1) ?: return settle.reject("bad arguments — MapView.fitPoints: options")) else null
                plugin.fitPoints(points, options, Reply<Unit, MapViewCode>(settle) { null })
            }
            "setPadding" -> {
                val padding = MapPadding.fromWire(args.opt(0)) ?: return settle.reject("bad arguments — MapView.setPadding: padding")
                plugin.setPadding(padding, Reply<Unit, MapViewCode>(settle) { null })
            }
            "getCamera" -> {
                plugin.getCamera(Reply<MapCamera, MapViewCode>(settle) { v -> v.wire })
            }
            "setUserLocation" -> {
                val a0 = args.opt(0)
                val lngLat = if (Wire.present(a0)) (Wire.array(a0, 2)?.let { v0 -> val v0_0 = Wire.f64(v0.opt(0)) ?: return@let null; val v0_1 = Wire.f64(v0.opt(1)) ?: return@let null; Pair(v0_0, v0_1) } ?: return settle.reject("bad arguments — MapView.setUserLocation: lngLat")) else null
                val a1 = args.opt(1)
                val options = if (Wire.present(a1)) (MapUserLocationOptions.fromWire(a1) ?: return settle.reject("bad arguments — MapView.setUserLocation: options")) else null
                plugin.setUserLocation(lngLat, options, Reply<Unit, MapViewCode>(settle) { null })
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
