// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.

package io.letary.lecodes.plugins.map

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.NativeViews
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Wire
import io.letary.lecodes.core.PackedReader
import io.letary.lecodes.core.PackedWriter

// ---- The contract's types ----

data class MapParams(
    /** A style URL the map fetches itself. */
    val style: String? = null,
    /**
     * A style as JSON text; wins over `style`. It has no base url: every url INSIDE it (sources,
     * sprite, glyphs) must be absolute.
     */
    val styleJson: String? = null,
    val center: Pair<Double, Double>? = null,
    /** Default 12 with a center. */
    val zoom: Double? = null,
    val minZoom: Double? = null,
    val maxZoom: Double? = null,
    /** Degrees clockwise from north. */
    val bearing: Double? = null,
    /** Degrees from the vertical. */
    val pitch: Double? = null,
    /** The two-finger rotate gesture. Default true. */
    val rotate: Boolean? = null,
    /** The two-finger tilt gesture. Default false. */
    val tilt: Boolean? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapParams? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: String? = null
            var m1: String? = null
            var m2: Pair<Double, Double>? = null
            var m3: Double? = null
            var m4: Double? = null
            var m5: Double? = null
            var m6: Double? = null
            var m7: Double? = null
            var m8: Boolean? = null
            var m9: Boolean? = null
            repeat(n) {
                when (r.key()) {
                    "style" -> if (r.isNull()) r.skip() else m0 = r.string() ?: return null
                    "styleJson" -> if (r.isNull()) r.skip() else m1 = r.string() ?: return null
                    "center" -> if (r.isNull()) r.skip() else m2 = r.tuple(2) {
                        val v0_0 = r.f64() ?: return@tuple null
                        val v0_1 = r.f64() ?: return@tuple null
                        Pair(v0_0, v0_1)
                    } ?: return null
                    "zoom" -> if (r.isNull()) r.skip() else m3 = r.f64() ?: return null
                    "minZoom" -> if (r.isNull()) r.skip() else m4 = r.f64() ?: return null
                    "maxZoom" -> if (r.isNull()) r.skip() else m5 = r.f64() ?: return null
                    "bearing" -> if (r.isNull()) r.skip() else m6 = r.f64() ?: return null
                    "pitch" -> if (r.isNull()) r.skip() else m7 = r.f64() ?: return null
                    "rotate" -> if (r.isNull()) r.skip() else m8 = r.bool() ?: return null
                    "tilt" -> if (r.isNull()) r.skip() else m9 = r.bool() ?: return null
                    else -> r.skip()
                }
            }
            return MapParams(style = m0, styleJson = m1, center = m2, zoom = m3, minZoom = m4, maxZoom = m5, bearing = m6, pitch = m7, rotate = m8, tilt = m9)
        }
    }
}

enum class MapLayerKind(val wire: String) {
    MARKERS("markers"),
    LINE("line");

    companion object {
        internal fun read(r: PackedReader): MapLayerKind? = r.string()?.let { s -> values().firstOrNull { it.wire == s } }
    }
}

/** The keys of both kinds; a half reads the ones of the kind it is asked for. */
data class MapLayerOptions(
    /** markers: group nearby markers (a cluster tap zooms in). Default false. */
    val cluster: Boolean? = null,
    /** markers: px. Default 50. */
    val clusterRadius: Double? = null,
    /** markers: the zoom at which clusters stop forming. */
    val clusterMaxZoom: Double? = null,
    /** line. */
    val color: String? = null,
    /** line: px. Default 4. */
    val width: Double? = null,
    /** line: 0–1. Default 1. */
    val opacity: Double? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapLayerOptions? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: Boolean? = null
            var m1: Double? = null
            var m2: Double? = null
            var m3: String? = null
            var m4: Double? = null
            var m5: Double? = null
            repeat(n) {
                when (r.key()) {
                    "cluster" -> if (r.isNull()) r.skip() else m0 = r.bool() ?: return null
                    "clusterRadius" -> if (r.isNull()) r.skip() else m1 = r.f64() ?: return null
                    "clusterMaxZoom" -> if (r.isNull()) r.skip() else m2 = r.f64() ?: return null
                    "color" -> if (r.isNull()) r.skip() else m3 = r.string() ?: return null
                    "width" -> if (r.isNull()) r.skip() else m4 = r.f64() ?: return null
                    "opacity" -> if (r.isNull()) r.skip() else m5 = r.f64() ?: return null
                    else -> r.skip()
                }
            }
            return MapLayerOptions(cluster = m0, clusterRadius = m1, clusterMaxZoom = m2, color = m3, width = m4, opacity = m5)
        }
    }
}

data class MapCameraMove(
    val zoom: Double? = null,
    val bearing: Double? = null,
    val pitch: Double? = null,
    /** flyTo only: ms. Default 600. */
    val duration: Double? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapCameraMove? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: Double? = null
            var m1: Double? = null
            var m2: Double? = null
            var m3: Double? = null
            repeat(n) {
                when (r.key()) {
                    "zoom" -> if (r.isNull()) r.skip() else m0 = r.f64() ?: return null
                    "bearing" -> if (r.isNull()) r.skip() else m1 = r.f64() ?: return null
                    "pitch" -> if (r.isNull()) r.skip() else m2 = r.f64() ?: return null
                    "duration" -> if (r.isNull()) r.skip() else m3 = r.f64() ?: return null
                    else -> r.skip()
                }
            }
            return MapCameraMove(zoom = m0, bearing = m1, pitch = m2, duration = m3)
        }
    }
}

/** Px, or a share of the view's size as "NN%". */
sealed class MapInset {
    data class OfNumber(val value: Double) : MapInset()
    data class OfString(val value: String) : MapInset()

    companion object {
        internal fun read(r: PackedReader): MapInset? = when (r.kind()) {
            PackedReader.NUMBER -> r.f64()?.let { OfNumber(it) }
            PackedReader.TEXT -> r.string()?.let { OfString(it) }
            else -> null
        }
    }
}

data class MapPadding(
    val top: MapInset? = null,
    val left: MapInset? = null,
    val bottom: MapInset? = null,
    val right: MapInset? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapPadding? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: MapInset? = null
            var m1: MapInset? = null
            var m2: MapInset? = null
            var m3: MapInset? = null
            repeat(n) {
                when (r.key()) {
                    "top" -> if (r.isNull()) r.skip() else m0 = MapInset.read(r) ?: return null
                    "left" -> if (r.isNull()) r.skip() else m1 = MapInset.read(r) ?: return null
                    "bottom" -> if (r.isNull()) r.skip() else m2 = MapInset.read(r) ?: return null
                    "right" -> if (r.isNull()) r.skip() else m3 = MapInset.read(r) ?: return null
                    else -> r.skip()
                }
            }
            return MapPadding(top = m0, left = m1, bottom = m2, right = m3)
        }
    }
}

sealed class MapFitOptionsPadding {
    data class OfNumber(val value: Double) : MapFitOptionsPadding()
    data class OfMapPadding(val value: MapPadding) : MapFitOptionsPadding()

    companion object {
        internal fun read(r: PackedReader): MapFitOptionsPadding? = when (r.kind()) {
            PackedReader.NUMBER -> r.f64()?.let { OfNumber(it) }
            PackedReader.MAP -> MapPadding.read(r)?.let { OfMapPadding(it) }
            else -> null
        }
    }
}

data class MapFitOptions(
    /** Around the points: px on every edge, or per edge. Added to the view padding. */
    val padding: MapFitOptionsPadding? = null,
    /** Default: 16 for one point, none otherwise. */
    val maxZoom: Double? = null,
    /** Default true. */
    val animate: Boolean? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapFitOptions? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: MapFitOptionsPadding? = null
            var m1: Double? = null
            var m2: Boolean? = null
            repeat(n) {
                when (r.key()) {
                    "padding" -> if (r.isNull()) r.skip() else m0 = MapFitOptionsPadding.read(r) ?: return null
                    "maxZoom" -> if (r.isNull()) r.skip() else m1 = r.f64() ?: return null
                    "animate" -> if (r.isNull()) r.skip() else m2 = r.bool() ?: return null
                    else -> r.skip()
                }
            }
            return MapFitOptions(padding = m0, maxZoom = m1, animate = m2)
        }
    }
}

data class MapCamera(
    val center: Pair<Double, Double>,
    val zoom: Double,
    val bearing: Double,
    val pitch: Double,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("center")
        w.beginArray()
        w.f64(this.center.first)
        w.f64(this.center.second)
        w.end()
        w.key("zoom"); w.f64(this.zoom)
        w.key("bearing"); w.f64(this.bearing)
        w.key("pitch"); w.f64(this.pitch)
        w.end()
    }
}

data class MapUserLocationOptions(
    /** Meters — the halo around the dot. */
    val accuracy: Double? = null,
    /** Degrees clockwise from north — the direction wedge; null hides it. */
    val heading: Double? = null,
) {
    companion object {
        internal fun read(r: PackedReader): MapUserLocationOptions? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: Double? = null
            var m1: Double? = null
            repeat(n) {
                when (r.key()) {
                    "accuracy" -> if (r.isNull()) r.skip() else m0 = r.f64() ?: return null
                    "heading" -> if (r.isNull()) r.skip() else m1 = r.f64() ?: return null
                    else -> r.skip()
                }
            }
            return MapUserLocationOptions(accuracy = m0, heading = m1)
        }
    }
}

sealed class MapFeatureId {
    data class OfString(val value: String) : MapFeatureId()
    data class OfNumber(val value: Double) : MapFeatureId()

    internal fun write(w: PackedWriter) {
        when (this) {
            is OfString -> w.string(value)
            is OfNumber -> w.f64(value)
        }
    }
}

/** A feature of a managed source under a tap. */
data class MapFeature(
    /** The source's name — the layer's name in the app. */
    val source: String,
    val id: MapFeatureId? = null,
    val properties: Map<String, Any>,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("source"); w.string(this.source)
        w.key("id")
        this.id.let { v0 -> if (v0 != null) v0.write(w) else w.nil() }
        w.key("properties")
        w.beginObject()
        for ((k0, v0) in this.properties) {
            w.key(k0)
            w.json(v0)
        }
        w.end()
        w.end()
    }
}

data class MapTap(
    val lngLat: Pair<Double, Double>,
    /** View-space point, logical px. */
    val point: Pair<Double, Double>,
    /**
     * Absent for a tap that hit no feature of a managed source. A tap on a CLUSTER zooms in and
     * sends no event.
     */
    val feature: MapFeature? = null,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("lngLat")
        w.beginArray()
        w.f64(this.lngLat.first)
        w.f64(this.lngLat.second)
        w.end()
        w.key("point")
        w.beginArray()
        w.f64(this.point.first)
        w.f64(this.point.second)
        w.end()
        this.feature?.let { v -> w.key("feature"); v.write(w) }
        w.end()
    }
}

// ---- MapView ----

/** The codes the calls of "map" reject with. */
enum class MapViewCode(override val code: String) : PluginCode {
    NOT_READY("notReady"),
    NO_POINTS("noPoints"),
}

/** The events of "map": what the plugin sends the app. From the main thread. */
class MapViewEvents(private val channel: PluginEmit) {
    /** The style loaded and the map takes calls. Fires again after every style reload. */
    fun ready() = channel.emit("ready", null)

    fun tap(payload: MapTap) {
        val w = PackedWriter()
        payload.write(w)
        channel.emit("tap", w.bytes())
    }

    /** The camera settled after a gesture or an animation. */
    fun moveEnd(payload: MapCamera) {
        val w = PackedWriter()
        payload.write(w)
        channel.emit("moveEnd", w.bytes())
    }

    /** A problem that is never fatal: a style that would not load, a source out of reach. */
    fun error(message: String) {
        val w = PackedWriter()
        w.beginObject()
        w.key("message"); w.string(message)
        w.end()
        this.channel.emit("error", w.bytes())
    }
}

/**
 * The view "map".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface MapViewPlugin {
    /** The view the host mounts: fullscreen, or embedded among a screen's children. */
    val view: android.view.View

    /**
     * Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
     * layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
     * Rejects with NOT_READY.
     */
    fun ensureLayer(source: String, kind: MapLayerKind, options: MapLayerOptions?, reply: Reply<Unit, MapViewCode>)

    fun removeLayer(source: String, reply: Reply<Unit, MapViewCode>)

    /**
     * Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
     * Rejects with NOT_READY.
     */
    fun setData(source: String, geojson: Any, reply: Reply<Unit, MapViewCode>)

    fun flyTo(center: Pair<Double, Double>, options: MapCameraMove?, reply: Reply<Unit, MapViewCode>)

    fun jumpTo(center: Pair<Double, Double>, options: MapCameraMove?, reply: Reply<Unit, MapViewCode>)

    /**
     * Fit the camera to the points.
     * Rejects with NO_POINTS.
     */
    fun fitPoints(points: List<Pair<Double, Double>>, options: MapFitOptions?, reply: Reply<Unit, MapViewCode>)

    /** The part of the view covered by the app's UI; camera moves center inside the rest. */
    fun setPadding(padding: MapPadding, reply: Reply<Unit, MapViewCode>)

    /** Rejects with NOT_READY. */
    fun getCamera(reply: Reply<MapCamera, MapViewCode>)

    /** Move the user puck; null hides it. */
    fun setUserLocation(lngLat: Pair<Double, Double>?, options: MapUserLocationOptions?, reply: Reply<Unit, MapViewCode>)

    /** The instance goes (the world swapped): release the hardware. */
    fun destroy() {}
}

object MapViewChannel {
    /** What the halves register under. */
    const val NAME = "map"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the view: `make` builds one instance from its params. */
    fun register(engine: LecodesEngine, make: (params: MapParams, events: MapViewEvents) -> MapViewPlugin) {
        engine.registerView(NAME, VERSION) { params, channel ->
            val plugin = make(MapParams.read(Wire.reader(params)) ?: MapParams(), MapViewEvents { event, packed -> channel.emitPacked(event, packed) })
            NativeViews.Instance(plugin.view, onCall = { call -> MapViewGlue.call(plugin, call.method, call.reader(), call) }, onDestroy = { plugin.destroy() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object MapViewGlue {
    fun call(plugin: MapViewPlugin, method: String, r: PackedReader, settle: ChannelSettle) {
        val n = r.beginArray()   // the arguments, in their order
        when (method) {
            "ensureLayer" -> {
                val a0 = (if (0 < n) r.string() else null) ?: return settle.reject("bad arguments — MapView.ensureLayer: source")
                val a1 = (if (1 < n) MapLayerKind.read(r) else null) ?: return settle.reject("bad arguments — MapView.ensureLayer: kind")
                val a2 = if (2 < n && !r.isNull()) (MapLayerOptions.read(r) ?: return settle.reject("bad arguments — MapView.ensureLayer: options")) else { if (2 < n) r.skip(); null }
                plugin.ensureLayer(a0, a1, a2, Reply<Unit, MapViewCode>(settle, null))
            }
            "removeLayer" -> {
                val a0 = (if (0 < n) r.string() else null) ?: return settle.reject("bad arguments — MapView.removeLayer: source")
                plugin.removeLayer(a0, Reply<Unit, MapViewCode>(settle, null))
            }
            "setData" -> {
                val a0 = (if (0 < n) r.string() else null) ?: return settle.reject("bad arguments — MapView.setData: source")
                val a1 = (if (1 < n) r.json() else null) ?: return settle.reject("bad arguments — MapView.setData: geojson")
                plugin.setData(a0, a1, Reply<Unit, MapViewCode>(settle, null))
            }
            "flyTo" -> {
                val a0 = (if (0 < n) r.tuple(2) {
                    val v0_0 = r.f64() ?: return@tuple null
                    val v0_1 = r.f64() ?: return@tuple null
                    Pair(v0_0, v0_1)
                } else null) ?: return settle.reject("bad arguments — MapView.flyTo: center")
                val a1 = if (1 < n && !r.isNull()) (MapCameraMove.read(r) ?: return settle.reject("bad arguments — MapView.flyTo: options")) else { if (1 < n) r.skip(); null }
                plugin.flyTo(a0, a1, Reply<Unit, MapViewCode>(settle, null))
            }
            "jumpTo" -> {
                val a0 = (if (0 < n) r.tuple(2) {
                    val v0_0 = r.f64() ?: return@tuple null
                    val v0_1 = r.f64() ?: return@tuple null
                    Pair(v0_0, v0_1)
                } else null) ?: return settle.reject("bad arguments — MapView.jumpTo: center")
                val a1 = if (1 < n && !r.isNull()) (MapCameraMove.read(r) ?: return settle.reject("bad arguments — MapView.jumpTo: options")) else { if (1 < n) r.skip(); null }
                plugin.jumpTo(a0, a1, Reply<Unit, MapViewCode>(settle, null))
            }
            "fitPoints" -> {
                val a0 = (if (0 < n) r.list {
                    r.tuple(2) {
                        val v1_0 = r.f64() ?: return@tuple null
                        val v1_1 = r.f64() ?: return@tuple null
                        Pair(v1_0, v1_1)
                    }
                } else null) ?: return settle.reject("bad arguments — MapView.fitPoints: points")
                val a1 = if (1 < n && !r.isNull()) (MapFitOptions.read(r) ?: return settle.reject("bad arguments — MapView.fitPoints: options")) else { if (1 < n) r.skip(); null }
                plugin.fitPoints(a0, a1, Reply<Unit, MapViewCode>(settle, null))
            }
            "setPadding" -> {
                val a0 = (if (0 < n) MapPadding.read(r) else null) ?: return settle.reject("bad arguments — MapView.setPadding: padding")
                plugin.setPadding(a0, Reply<Unit, MapViewCode>(settle, null))
            }
            "getCamera" -> {
                plugin.getCamera(Reply<MapCamera, MapViewCode>(settle) { v, w -> v.write(w) })
            }
            "setUserLocation" -> {
                val a0 = if (0 < n && !r.isNull()) (r.tuple(2) {
                    val v0_0 = r.f64() ?: return@tuple null
                    val v0_1 = r.f64() ?: return@tuple null
                    Pair(v0_0, v0_1)
                } ?: return settle.reject("bad arguments — MapView.setUserLocation: lngLat")) else { if (0 < n) r.skip(); null }
                val a1 = if (1 < n && !r.isNull()) (MapUserLocationOptions.read(r) ?: return settle.reject("bad arguments — MapView.setUserLocation: options")) else { if (1 < n) r.skip(); null }
                plugin.setUserLocation(a0, a1, Reply<Unit, MapViewCode>(settle, null))
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
