// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.

import { ViewChannel, type Json } from "lecodes-sdk/plugin"
import type { LngLat, MapCamera, MapCameraMove, MapEvents, MapFitOptions, MapLayerKind, MapLayerOptions, MapPadding, MapParams, MapUserLocationOptions } from "../contract"

/** What the halves register under. */
export const NAME = "map"
/** The contract's version: the highest `@since` of its members. */
export const VERSION = 1

// ---- the wire, call by call ----------------------------------------------------------------------

/** Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
 *  layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
 *  Rejects with "notReady". */
export const ensureLayer = (view: ViewChannel<MapEvents>, source: string, kind: MapLayerKind, options?: MapLayerOptions): Promise<void> =>
  view._call("ensureLayer", [source, kind, options], 1, true)

export const removeLayer = (view: ViewChannel<MapEvents>, source: string): Promise<void> =>
  view._call("removeLayer", [source], 1, true)

/** Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
 *  Rejects with "notReady". */
export const setData = (view: ViewChannel<MapEvents>, source: string, geojson: Json): Promise<void> =>
  view._call("setData", [source, geojson], 1, true)

export const flyTo = (view: ViewChannel<MapEvents>, center: LngLat, options?: MapCameraMove): Promise<void> =>
  view._call("flyTo", [center, options], 1, true)

export const jumpTo = (view: ViewChannel<MapEvents>, center: LngLat, options?: MapCameraMove): Promise<void> =>
  view._call("jumpTo", [center, options], 1, true)

/** Fit the camera to the points.
 *  Rejects with "noPoints". */
export const fitPoints = (view: ViewChannel<MapEvents>, points: LngLat[], options?: MapFitOptions): Promise<void> =>
  view._call("fitPoints", [points, options], 1, true)

/** The part of the view covered by the app's UI; camera moves center inside the rest. */
export const setPadding = (view: ViewChannel<MapEvents>, padding: MapPadding): Promise<void> =>
  view._call("setPadding", [padding], 1, true)

/** Rejects with "notReady". */
export const getCamera = (view: ViewChannel<MapEvents>): Promise<MapCamera> =>
  view._call("getCamera", [], 1, true)

/** Move the user puck; null hides it. */
export const setUserLocation = (view: ViewChannel<MapEvents>, lngLat: LngLat | null, options?: MapUserLocationOptions): Promise<void> =>
  view._call("setUserLocation", [lngLat, options], 1, true)

// ---- what the host's half has --------------------------------------------------------------------

/** A method of the contract. */
export type Method = "ensureLayer" | "removeLayer" | "setData" | "flyTo" | "jumpTo" | "fitPoints" | "setPadding" | "getCamera" | "setUserLocation"

/** Whether this host has the view "map" — and, given a method, a half new enough for it
 *  (a method added after the first version of the contract is tagged `@since`). */
export const supports = (method?: Method): boolean =>
  ViewChannel.supports(NAME)   // every method is of version 1

// ---- the element ----------------------------------------------------------------------------------

/** The view "map" with the wire's methods as its own. */
export class MapViewBase extends ViewChannel<MapEvents> {
  constructor(params: MapParams = {}) { super("MapView", NAME, params) }

  /** Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
   *  layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
   *  Rejects with "notReady". */
  ensureLayer(source: string, kind: MapLayerKind, options?: MapLayerOptions): Promise<void> { return ensureLayer(this, source, kind, options) }
  removeLayer(source: string): Promise<void> { return removeLayer(this, source) }
  /** Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
   *  Rejects with "notReady". */
  setData(source: string, geojson: Json): Promise<void> { return setData(this, source, geojson) }
  flyTo(center: LngLat, options?: MapCameraMove): Promise<void> { return flyTo(this, center, options) }
  jumpTo(center: LngLat, options?: MapCameraMove): Promise<void> { return jumpTo(this, center, options) }
  /** Fit the camera to the points.
   *  Rejects with "noPoints". */
  fitPoints(points: LngLat[], options?: MapFitOptions): Promise<void> { return fitPoints(this, points, options) }
  /** The part of the view covered by the app's UI; camera moves center inside the rest. */
  setPadding(padding: MapPadding): Promise<void> { return setPadding(this, padding) }
  /** Rejects with "notReady". */
  getCamera(): Promise<MapCamera> { return getCamera(this) }
  /** Move the user puck; null hides it. */
  setUserLocation(lngLat: LngLat | null, options?: MapUserLocationOptions): Promise<void> { return setUserLocation(this, lngLat, options) }
}
