// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// camera: the view "camera", contract version 1.

package io.letary.lecodes.plugins.camera

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.NativeViews
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.PluginFile
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Wire
import org.json.JSONArray
import org.json.JSONObject

// ---- The contract's types ----

enum class Facing(val wire: String) {
    FRONT("front"),
    BACK("back");

    companion object {
        internal fun fromWire(wire: Any?): Facing? = values().firstOrNull { it.wire == wire }
    }
}

data class CameraParams(
    /** Default "back". */
    val facingMode: Facing? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): CameraParams? {
            val o = Wire.obj(wire) ?: return null
            val facingMode = if (Wire.present(o.opt("facingMode"))) (Facing.fromWire(o.opt("facingMode")) ?: return null) else null
            return CameraParams(facingMode = facingMode)
        }
    }
}

// ---- CameraView ----

/** The codes the calls of "camera" reject with. */
enum class CameraViewCode(override val code: String) : PluginCode {
    FAILED("failed"),
}

/** The events of "camera": what the plugin sends the app. From the main thread. */
class CameraViewEvents(private val channel: PluginEmit) {
    /** The preview could not start or stopped (no camera, the stream was refused). */
    fun error(message: String) {
        val o = JSONObject()
        o.put("message", message)
        channel.emit("error", o.toString())
    }
}

/**
 * The view "camera".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface CameraViewPlugin {
    /** The view the host mounts: fullscreen, or embedded among a screen's children. */
    val view: android.view.View

    /**
     * Capture a still frame as a JPEG.
     * Rejects with FAILED.
     */
    fun takePhoto(reply: Reply<PluginFile, CameraViewCode>)

    /** Switch the camera while the preview is live. */
    fun setFacingMode(mode: Facing, reply: Reply<Unit, CameraViewCode>)

    /** The instance goes (the world swapped): release the hardware. */
    fun destroy() {}
}

object CameraViewChannel {
    /** What the halves register under. */
    const val NAME = "camera"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the view: `make` builds one instance from its params. */
    fun register(engine: LecodesEngine, make: (params: CameraParams, events: CameraViewEvents) -> CameraViewPlugin) {
        engine.registerView(NAME) { params, channel ->
            val plugin = make(CameraParams.fromWire(params) ?: CameraParams(), CameraViewEvents { event, data -> channel.emit(event, data) })
            NativeViews.Instance(plugin.view, onCall = { call -> CameraViewGlue.call(plugin, call.method, call.args, call) }, onDestroy = { plugin.destroy() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object CameraViewGlue {
    fun call(plugin: CameraViewPlugin, method: String, args: JSONArray, settle: ChannelSettle) {
        when (method) {
            "takePhoto" -> {
                plugin.takePhoto(Reply<PluginFile, CameraViewCode>(settle) { v -> v.wire })
            }
            "setFacingMode" -> {
                val mode = Facing.fromWire(args.opt(0)) ?: return settle.reject("bad arguments — CameraView.setFacingMode: mode")
                plugin.setFacingMode(mode, Reply<Unit, CameraViewCode>(settle) { null })
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
