// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// camera: the view "camera", contract version 1.

import Foundation
import UIKit
import LeCodes

// MARK: - The contract's types

public enum Facing: String {
    case front
    case back

    init?(wire: WireIn) {
        guard let raw = wire.string, let value = Facing(rawValue: raw) else { return nil }
        self = value
    }
}

public struct CameraParams {
    /// Default "back".
    public var facingMode: Facing?

    public init(facingMode: Facing? = nil) {
        self.facingMode = facingMode
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["facingMode", 0]
        if m0.isPresent {
            guard let v = Facing(wire: m0) else { return nil }
            self.facingMode = v
        } else {
            self.facingMode = nil
        }
    }
}

// MARK: - CameraView

/// The codes the calls of "camera" reject with.
public enum CameraViewCode: String, PluginCode {
    case failed
}

/// The events of "camera": what the plugin sends the app. Any thread.
public struct CameraViewEvents {
    let channel: NativeViewChannel

    /// The preview could not start or stopped (no camera, the stream was refused).
    public func error(message: String) {
        self.channel.emit("error") { w in
            w.beginObject(1)
            w.key("message"); w.string(message)
            w.end()
        }
    }
}

/// The view "camera".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol CameraViewPlugin: AnyObject {
    /// The view the host mounts: fullscreen, or embedded among a screen's children.
    var view: UIView { get }

    /// Capture a still frame as a JPEG.
    /// Rejects with .failed.
    func takePhoto(_ reply: Reply<PluginFile, CameraViewCode>)
    /// Switch the camera while the preview is live.
    func setFacingMode(_ mode: Facing, _ reply: Reply<Void, CameraViewCode>)

    /// The instance goes (the world swapped): release the hardware.
    func destroy()
}

public extension CameraViewPlugin {
    func destroy() {}
}

public enum CameraViewChannel {
    /// What the halves register under.
    public static let name = "camera"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the view: `make` builds one instance from its params.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (CameraParams, CameraViewEvents) -> CameraViewPlugin) {
        engine.registerView(name, version: Int32(version)) { params, channel in
            CameraViewGlue(make(WireIn.of(params, { CameraParams(wire: $0) }) ?? CameraParams(), CameraViewEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class CameraViewGlue: WireNativeViewInstance {
    private let plugin: CameraViewPlugin

    init(_ plugin: CameraViewPlugin) { self.plugin = plugin }

    var view: UIView { plugin.view }

    func call(_ method: String, wire args: WireIn, _ settle: ChannelSettle) {
        switch method {
        case "takePhoto":
            plugin.takePhoto(Reply<PluginFile, CameraViewCode>(settle) { v, w in v.write(to: w) })
        case "setFacingMode":
            guard let a0 = Facing(wire: args[0]) else { return settle.reject("bad arguments — CameraView.setFacingMode: mode") }
            plugin.setFacingMode(a0, Reply<Void, CameraViewCode>(settle))
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func destroy() { plugin.destroy() }
}
