// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// qr-scanner: the view "qrScanner", contract version 1.

import Foundation
import UIKit
import LeCodes

// MARK: - The contract's types

public struct QRScannerParams {
    public init() {}

    init?(wire: Any?) {
        guard wire == nil || wire is NSNull || Wire.object(wire) != nil else { return nil }
    }
}

// MARK: - QRScanner

/// The events of "qrScanner": what the plugin sends the app. Any thread.
public struct QRScannerEvents {
    let channel: NativeViewChannel

    /// One per decoded camera frame: the payload, or null for a frame with no readable code (it
    /// repeats while the user aims). The same code may be reported more than once.
    public func scan(data: String? = nil) {
        var o: [String: Any] = [:]
        if let v = data { o["data"] = v } else { o["data"] = NSNull() }
        channel.emit("scan", o)
    }
}

/// The view "qrScanner".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol QRScannerPlugin: AnyObject {
    /// The view the host mounts: fullscreen, or embedded among a screen's children.
    var view: UIView { get }

    /// The instance goes (the world swapped): release the hardware.
    func destroy()
}

public extension QRScannerPlugin {
    func destroy() {}
}

public enum QRScannerChannel {
    /// What the halves register under.
    public static let name = "qrScanner"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the view: `make` builds one instance from its params.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (QRScannerParams, QRScannerEvents) -> QRScannerPlugin) {
        engine.registerView(name, version: Int32(version)) { params, channel in
            QRScannerGlue(make(QRScannerParams(wire: params) ?? QRScannerParams(), QRScannerEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class QRScannerGlue: NativeViewInstance {
    private let plugin: QRScannerPlugin

    init(_ plugin: QRScannerPlugin) { self.plugin = plugin }

    var view: UIView { plugin.view }

    func call(_ method: String, _ args: [Any], _ settle: ChannelSettle) {
        switch method {
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func destroy() { plugin.destroy() }
}
