// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.
//
// The web half's side of the channel. This file imports nothing: a half depends on it, on the
// document it is handed and on the browser.

// ---- what the host hands a half ----

/** Where a half's events go. */
export interface PluginChannel { emit(event: string, data?: unknown): void }

/** The host, as a half needs it: a SHAPE — the host's own type is never imported. */
export interface PluginHost {
  registerView(name: string, factory: (params: unknown, channel: PluginChannel, doc: Document) => {
    el: HTMLElement, call?(method: string, args: unknown[]): unknown, destroy?(): void,
  }): void
}

/** A value the generator passes through untyped. */
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json }

// The readers of the wire's values: undefined = absent, null, or not that type.
const wire = {
  present: (v: unknown): boolean => v !== undefined && v !== null,
  f64: (v: unknown): number | undefined => typeof v === "number" ? v : undefined,
  i32: (v: unknown): number | undefined =>
    typeof v === "number" && Number.isInteger(v) && v >= -2147483648 && v <= 2147483647 ? v : undefined,
  bool: (v: unknown): boolean | undefined => typeof v === "boolean" ? v : undefined,
  string: (v: unknown): string | undefined => typeof v === "string" ? v : undefined,
  /** Any JSON value, as it is; a null is a value here. */
  json: (v: unknown): any => v,
  object: (v: unknown): Record<string, unknown> | undefined =>
    typeof v === "object" && v !== null && !Array.isArray(v) ? v as Record<string, unknown> : undefined,
  /** An array of exactly `count` values (a tuple), or of any length. */
  array: (v: unknown, count?: number): unknown[] | undefined =>
    Array.isArray(v) && (count === undefined || v.length === count) ? v : undefined,
  /** Every element or nothing: one that does not read fails the list. */
  list: <T>(v: unknown, each: (v: unknown) => T | undefined): T[] | undefined => {
    if (!Array.isArray(v)) return undefined
    const out: T[] = []
    for (const item of v) {
      const r = each(item)
      if (r === undefined) return undefined
      out.push(r)
    }
    return out
  },
  map: <T>(v: unknown, each: (v: unknown) => T | undefined): { [key: string]: T } | undefined => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) return undefined
    const out: { [key: string]: T } = {}
    for (const [k, item] of Object.entries(v)) {
      const r = each(item)
      if (r === undefined) return undefined
      out[k] = r
    }
    return out
  },
}

// ---- the contract's types ----

export interface MapParams {
  /** A style URL the map fetches itself. */
  style?: string
  /** A style as JSON text; wins over `style`. It has no base url: every url INSIDE it (sources,
   *  sprite, glyphs) must be absolute. */
  styleJson?: string
  center?: [number, number]
  /** Default 12 with a center. */
  zoom?: number
  minZoom?: number
  maxZoom?: number
  /** Degrees clockwise from north. */
  bearing?: number
  /** Degrees from the vertical. */
  pitch?: number
  /** The two-finger rotate gesture. Default true. */
  rotate?: boolean
  /** The two-finger tilt gesture. Default false. */
  tilt?: boolean
}
const readMapParams = (v: unknown): MapParams | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: string | undefined = undefined
  if (wire.present(o.style)) {
    const r = wire.string(o.style)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: string | undefined = undefined
  if (wire.present(o.styleJson)) {
    const r = wire.string(o.styleJson)
    if (r === undefined) return undefined
    f1 = r
  }
  let f2: [number, number] | undefined = undefined
  if (wire.present(o.center)) {
    const r = ((v0): [number, number] | undefined => { if (!v0) return undefined; const v0_0 = wire.f64(v0[0]); if (v0_0 === undefined) return undefined; const v0_1 = wire.f64(v0[1]); if (v0_1 === undefined) return undefined; return [v0_0, v0_1] })(wire.array(o.center, 2))
    if (r === undefined) return undefined
    f2 = r
  }
  let f3: number | undefined = undefined
  if (wire.present(o.zoom)) {
    const r = wire.f64(o.zoom)
    if (r === undefined) return undefined
    f3 = r
  }
  let f4: number | undefined = undefined
  if (wire.present(o.minZoom)) {
    const r = wire.f64(o.minZoom)
    if (r === undefined) return undefined
    f4 = r
  }
  let f5: number | undefined = undefined
  if (wire.present(o.maxZoom)) {
    const r = wire.f64(o.maxZoom)
    if (r === undefined) return undefined
    f5 = r
  }
  let f6: number | undefined = undefined
  if (wire.present(o.bearing)) {
    const r = wire.f64(o.bearing)
    if (r === undefined) return undefined
    f6 = r
  }
  let f7: number | undefined = undefined
  if (wire.present(o.pitch)) {
    const r = wire.f64(o.pitch)
    if (r === undefined) return undefined
    f7 = r
  }
  let f8: boolean | undefined = undefined
  if (wire.present(o.rotate)) {
    const r = wire.bool(o.rotate)
    if (r === undefined) return undefined
    f8 = r
  }
  let f9: boolean | undefined = undefined
  if (wire.present(o.tilt)) {
    const r = wire.bool(o.tilt)
    if (r === undefined) return undefined
    f9 = r
  }
  const out: MapParams = {}
  if (f0 !== undefined) out.style = f0
  if (f1 !== undefined) out.styleJson = f1
  if (f2 !== undefined) out.center = f2
  if (f3 !== undefined) out.zoom = f3
  if (f4 !== undefined) out.minZoom = f4
  if (f5 !== undefined) out.maxZoom = f5
  if (f6 !== undefined) out.bearing = f6
  if (f7 !== undefined) out.pitch = f7
  if (f8 !== undefined) out.rotate = f8
  if (f9 !== undefined) out.tilt = f9
  return out
}

export type MapLayerKind = "markers" | "line"
const readMapLayerKind = (v: unknown): MapLayerKind | undefined =>
  v === "markers" || v === "line" ? v : undefined

/** The keys of both kinds; a half reads the ones of the kind it is asked for. */
export interface MapLayerOptions {
  /** markers: group nearby markers (a cluster tap zooms in). Default false. */
  cluster?: boolean
  /** markers: px. Default 50. */
  clusterRadius?: number
  /** markers: the zoom at which clusters stop forming. */
  clusterMaxZoom?: number
  /** line. */
  color?: string
  /** line: px. Default 4. */
  width?: number
  /** line: 0–1. Default 1. */
  opacity?: number
}
const readMapLayerOptions = (v: unknown): MapLayerOptions | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: boolean | undefined = undefined
  if (wire.present(o.cluster)) {
    const r = wire.bool(o.cluster)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: number | undefined = undefined
  if (wire.present(o.clusterRadius)) {
    const r = wire.f64(o.clusterRadius)
    if (r === undefined) return undefined
    f1 = r
  }
  let f2: number | undefined = undefined
  if (wire.present(o.clusterMaxZoom)) {
    const r = wire.f64(o.clusterMaxZoom)
    if (r === undefined) return undefined
    f2 = r
  }
  let f3: string | undefined = undefined
  if (wire.present(o.color)) {
    const r = wire.string(o.color)
    if (r === undefined) return undefined
    f3 = r
  }
  let f4: number | undefined = undefined
  if (wire.present(o.width)) {
    const r = wire.f64(o.width)
    if (r === undefined) return undefined
    f4 = r
  }
  let f5: number | undefined = undefined
  if (wire.present(o.opacity)) {
    const r = wire.f64(o.opacity)
    if (r === undefined) return undefined
    f5 = r
  }
  const out: MapLayerOptions = {}
  if (f0 !== undefined) out.cluster = f0
  if (f1 !== undefined) out.clusterRadius = f1
  if (f2 !== undefined) out.clusterMaxZoom = f2
  if (f3 !== undefined) out.color = f3
  if (f4 !== undefined) out.width = f4
  if (f5 !== undefined) out.opacity = f5
  return out
}

export interface MapCameraMove {
  zoom?: number
  bearing?: number
  pitch?: number
  /** flyTo only: ms. Default 600. */
  duration?: number
}
const readMapCameraMove = (v: unknown): MapCameraMove | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: number | undefined = undefined
  if (wire.present(o.zoom)) {
    const r = wire.f64(o.zoom)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: number | undefined = undefined
  if (wire.present(o.bearing)) {
    const r = wire.f64(o.bearing)
    if (r === undefined) return undefined
    f1 = r
  }
  let f2: number | undefined = undefined
  if (wire.present(o.pitch)) {
    const r = wire.f64(o.pitch)
    if (r === undefined) return undefined
    f2 = r
  }
  let f3: number | undefined = undefined
  if (wire.present(o.duration)) {
    const r = wire.f64(o.duration)
    if (r === undefined) return undefined
    f3 = r
  }
  const out: MapCameraMove = {}
  if (f0 !== undefined) out.zoom = f0
  if (f1 !== undefined) out.bearing = f1
  if (f2 !== undefined) out.pitch = f2
  if (f3 !== undefined) out.duration = f3
  return out
}

/** Px, or a share of the view's size as "NN%". */
export type MapInset = number | string
const readMapInset = (v: unknown): MapInset | undefined =>
  wire.f64(v) ?? wire.string(v)

export interface MapPadding {
  top?: MapInset
  left?: MapInset
  bottom?: MapInset
  right?: MapInset
}
const readMapPadding = (v: unknown): MapPadding | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: MapInset | undefined = undefined
  if (wire.present(o.top)) {
    const r = readMapInset(o.top)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: MapInset | undefined = undefined
  if (wire.present(o.left)) {
    const r = readMapInset(o.left)
    if (r === undefined) return undefined
    f1 = r
  }
  let f2: MapInset | undefined = undefined
  if (wire.present(o.bottom)) {
    const r = readMapInset(o.bottom)
    if (r === undefined) return undefined
    f2 = r
  }
  let f3: MapInset | undefined = undefined
  if (wire.present(o.right)) {
    const r = readMapInset(o.right)
    if (r === undefined) return undefined
    f3 = r
  }
  const out: MapPadding = {}
  if (f0 !== undefined) out.top = f0
  if (f1 !== undefined) out.left = f1
  if (f2 !== undefined) out.bottom = f2
  if (f3 !== undefined) out.right = f3
  return out
}

export type MapFitOptionsPadding = number | MapPadding
const readMapFitOptionsPadding = (v: unknown): MapFitOptionsPadding | undefined =>
  wire.f64(v) ?? readMapPadding(v)

export interface MapFitOptions {
  /** Around the points: px on every edge, or per edge. Added to the view padding. */
  padding?: MapFitOptionsPadding
  /** Default: 16 for one point, none otherwise. */
  maxZoom?: number
  /** Default true. */
  animate?: boolean
}
const readMapFitOptions = (v: unknown): MapFitOptions | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: MapFitOptionsPadding | undefined = undefined
  if (wire.present(o.padding)) {
    const r = readMapFitOptionsPadding(o.padding)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: number | undefined = undefined
  if (wire.present(o.maxZoom)) {
    const r = wire.f64(o.maxZoom)
    if (r === undefined) return undefined
    f1 = r
  }
  let f2: boolean | undefined = undefined
  if (wire.present(o.animate)) {
    const r = wire.bool(o.animate)
    if (r === undefined) return undefined
    f2 = r
  }
  const out: MapFitOptions = {}
  if (f0 !== undefined) out.padding = f0
  if (f1 !== undefined) out.maxZoom = f1
  if (f2 !== undefined) out.animate = f2
  return out
}

export interface MapCamera {
  center: [number, number]
  zoom: number
  bearing: number
  pitch: number
}

export interface MapUserLocationOptions {
  /** Meters — the halo around the dot. */
  accuracy?: number
  /** Degrees clockwise from north — the direction wedge; null hides it. */
  heading?: number
}
const readMapUserLocationOptions = (v: unknown): MapUserLocationOptions | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: number | undefined = undefined
  if (wire.present(o.accuracy)) {
    const r = wire.f64(o.accuracy)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: number | undefined = undefined
  if (wire.present(o.heading)) {
    const r = wire.f64(o.heading)
    if (r === undefined) return undefined
    f1 = r
  }
  const out: MapUserLocationOptions = {}
  if (f0 !== undefined) out.accuracy = f0
  if (f1 !== undefined) out.heading = f1
  return out
}

export type MapFeatureId = string | number

/** A feature of a managed source under a tap. */
export interface MapFeature {
  /** The source's name — the layer's name in the app. */
  source: string
  id: MapFeatureId | null
  properties: { [key: string]: Json }
}

export interface MapTap {
  lngLat: [number, number]
  /** View-space point, logical px. */
  point: [number, number]
  /** Absent for a tap that hit no feature of a managed source. A tap on a CLUSTER zooms in and
   *  sends no event. */
  feature?: MapFeature
}

// ---- MapView ----

/** The codes the calls of "map" reject with. */
export type MapViewCode = "notReady" | "noPoints"

/** What a call throws to reject with a code of the contract — the app's promise rejects with it
 *  as the message. Any other error is a message the contract has no code for. */
export class MapViewError extends Error {
  constructor(readonly code: MapViewCode) { super(code) }
}

/** The events of "map": what the half sends the app. */
export interface MapViewEvents {
  /** The style loaded and the map takes calls. Fires again after every style reload. */
  ready(): void
  tap(payload: MapTap): void
  /** The camera settled after a gesture or an animation. */
  moveEnd(payload: MapCamera): void
  /** A problem that is never fatal: a style that would not load, a source out of reach. */
  error(payload: { message: string }): void
}

/** The view "map".
 *
 *  What the half implements. A call returns its result, or a promise of it; it rejects by throwing. */
export interface MapViewPlugin {
  /** The element the host mounts. The half fills it and follows its size itself. */
  readonly el: HTMLElement
  /** Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
   *  layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
   *  Rejects with "notReady". */
  ensureLayer(source: string, kind: MapLayerKind, options?: MapLayerOptions): void | Promise<void>
  removeLayer(source: string): void | Promise<void>
  /** Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
   *  Rejects with "notReady". */
  setData(source: string, geojson: Json): void | Promise<void>
  flyTo(center: [number, number], options?: MapCameraMove): void | Promise<void>
  jumpTo(center: [number, number], options?: MapCameraMove): void | Promise<void>
  /** Fit the camera to the points.
   *  Rejects with "noPoints". */
  fitPoints(points: [number, number][], options?: MapFitOptions): void | Promise<void>
  /** The part of the view covered by the app's UI; camera moves center inside the rest. */
  setPadding(padding: MapPadding): void | Promise<void>
  /** Rejects with "notReady". */
  getCamera(): MapCamera | Promise<MapCamera>
  /** Move the user puck; null hides it. */
  setUserLocation(lngLat: [number, number] | null, options?: MapUserLocationOptions): void | Promise<void>
  /** The instance goes (the world swapped): release the hardware. */
  destroy?(): void
}

export const MapViewChannel = {
  /** What the halves register under. */
  name: "map",
  /** The contract's version: the highest `@since` of its members. */
  version: 1,
} as const

/** Register the view: `make` builds one instance from its params, in the document it is handed. */
export const registerMapView = (host: PluginHost, make: (params: MapParams, events: MapViewEvents, doc: Document) => MapViewPlugin): void => {
  host.registerView(MapViewChannel.name, (params, channel, doc) => {
    const events: MapViewEvents = {
      ready: () => channel.emit("ready"),
      tap: (payload) => channel.emit("tap", payload),
      moveEnd: (payload) => channel.emit("moveEnd", payload),
      error: (payload) => channel.emit("error", payload),
    }
    const plugin = make(readMapParams(params) ?? {}, events, doc)
    const call = async (method: string, args: unknown[]): Promise<unknown> => {
      switch (method) {
        case "ensureLayer": {
          const a0 = wire.string(args[0])
          if (a0 === undefined) throw new Error("bad arguments — MapView.ensureLayer: source")
          const a1 = readMapLayerKind(args[1])
          if (a1 === undefined) throw new Error("bad arguments — MapView.ensureLayer: kind")
          let a2: MapLayerOptions | undefined = undefined
          if (wire.present(args[2])) {
            const r = readMapLayerOptions(args[2])
            if (r === undefined) throw new Error("bad arguments — MapView.ensureLayer: options")
            a2 = r
          }
          await plugin.ensureLayer(a0, a1, a2)
          return undefined
        }
        case "removeLayer": {
          const a0 = wire.string(args[0])
          if (a0 === undefined) throw new Error("bad arguments — MapView.removeLayer: source")
          await plugin.removeLayer(a0)
          return undefined
        }
        case "setData": {
          const a0 = wire.string(args[0])
          if (a0 === undefined) throw new Error("bad arguments — MapView.setData: source")
          const a1 = wire.json(args[1])
          if (a1 === undefined) throw new Error("bad arguments — MapView.setData: geojson")
          await plugin.setData(a0, a1)
          return undefined
        }
        case "flyTo": {
          const a0 = ((v0): [number, number] | undefined => { if (!v0) return undefined; const v0_0 = wire.f64(v0[0]); if (v0_0 === undefined) return undefined; const v0_1 = wire.f64(v0[1]); if (v0_1 === undefined) return undefined; return [v0_0, v0_1] })(wire.array(args[0], 2))
          if (a0 === undefined) throw new Error("bad arguments — MapView.flyTo: center")
          let a1: MapCameraMove | undefined = undefined
          if (wire.present(args[1])) {
            const r = readMapCameraMove(args[1])
            if (r === undefined) throw new Error("bad arguments — MapView.flyTo: options")
            a1 = r
          }
          await plugin.flyTo(a0, a1)
          return undefined
        }
        case "jumpTo": {
          const a0 = ((v0): [number, number] | undefined => { if (!v0) return undefined; const v0_0 = wire.f64(v0[0]); if (v0_0 === undefined) return undefined; const v0_1 = wire.f64(v0[1]); if (v0_1 === undefined) return undefined; return [v0_0, v0_1] })(wire.array(args[0], 2))
          if (a0 === undefined) throw new Error("bad arguments — MapView.jumpTo: center")
          let a1: MapCameraMove | undefined = undefined
          if (wire.present(args[1])) {
            const r = readMapCameraMove(args[1])
            if (r === undefined) throw new Error("bad arguments — MapView.jumpTo: options")
            a1 = r
          }
          await plugin.jumpTo(a0, a1)
          return undefined
        }
        case "fitPoints": {
          const a0 = wire.list(args[0], (v0) => ((v1): [number, number] | undefined => { if (!v1) return undefined; const v1_0 = wire.f64(v1[0]); if (v1_0 === undefined) return undefined; const v1_1 = wire.f64(v1[1]); if (v1_1 === undefined) return undefined; return [v1_0, v1_1] })(wire.array(v0, 2)))
          if (a0 === undefined) throw new Error("bad arguments — MapView.fitPoints: points")
          let a1: MapFitOptions | undefined = undefined
          if (wire.present(args[1])) {
            const r = readMapFitOptions(args[1])
            if (r === undefined) throw new Error("bad arguments — MapView.fitPoints: options")
            a1 = r
          }
          await plugin.fitPoints(a0, a1)
          return undefined
        }
        case "setPadding": {
          const a0 = readMapPadding(args[0])
          if (a0 === undefined) throw new Error("bad arguments — MapView.setPadding: padding")
          await plugin.setPadding(a0)
          return undefined
        }
        case "getCamera": {
          return await plugin.getCamera()
        }
        case "setUserLocation": {
          let a0: [number, number] | null = null
          if (wire.present(args[0])) {
            const r = ((v0): [number, number] | undefined => { if (!v0) return undefined; const v0_0 = wire.f64(v0[0]); if (v0_0 === undefined) return undefined; const v0_1 = wire.f64(v0[1]); if (v0_1 === undefined) return undefined; return [v0_0, v0_1] })(wire.array(args[0], 2))
            if (r === undefined) throw new Error("bad arguments — MapView.setUserLocation: lngLat")
            a0 = r
          }
          let a1: MapUserLocationOptions | undefined = undefined
          if (wire.present(args[1])) {
            const r = readMapUserLocationOptions(args[1])
            if (r === undefined) throw new Error("bad arguments — MapView.setUserLocation: options")
            a1 = r
          }
          await plugin.setUserLocation(a0, a1)
          return undefined
        }
        default: throw new Error(`Unknown method: ${method}`)
      }
    }
    return { el: plugin.el, call, destroy: () => plugin.destroy?.() }
  })
}
