// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// qr-scanner: the view "qrScanner", contract version 1.
//
// The web half's side of the channel. This file imports nothing: a half depends on it, on the
// document it is handed and on the browser.

// ---- what the host hands a half ----

/** Where a half's events go. */
export interface PluginChannel { emit(event: string, data?: unknown): void }

/** The host, as a half needs it: a SHAPE — the host's own type is never imported. */
export interface PluginHost {
  // `version` = the contract version the half was generated from: what the app's `supports()` asks.
  registerView(name: string, factory: (params: unknown, channel: PluginChannel, doc: Document) => {
    el: HTMLElement, call?(method: string, args: unknown[]): unknown, destroy?(): void,
  }, version: number): void
}

// The readers of the wire's values: undefined = absent, null, or not that type. On the web the wire
// carries the app's OWN values (the host is JavaScript like the app). What is read of the contract is
// built anew — a struct, a list, bytes — so what a half keeps is its own; a Json value alone is the
// app's object, as it is.
const wire = {
  present: (v: unknown): boolean => v !== undefined && v !== null,
  /** A number that is not finite is a null on the wire, as JSON has it. */
  f64: (v: unknown): number | undefined => typeof v === "number" && Number.isFinite(v) ? v : undefined,
  i32: (v: unknown): number | undefined =>
    typeof v === "number" && Number.isInteger(v) && v >= -2147483648 && v <= 2147483647 ? v : undefined,
  bool: (v: unknown): boolean | undefined => typeof v === "boolean" ? v : undefined,
  string: (v: unknown): string | undefined => typeof v === "string" ? v : undefined,
  /** Any JSON value, as it is; a null is a value here. */
  json: (v: unknown): any => v,
  /** A copy of the bytes. Told by its class name, not `instanceof`: the app's realm may not be the half's. */
  bytes: (v: unknown): Uint8Array | undefined =>
    Object.prototype.toString.call(v) === "[object Uint8Array]" ? (v as Uint8Array).slice() : undefined,
  object: (v: unknown): Record<string, unknown> | undefined =>
    typeof v === "object" && v !== null && !Array.isArray(v) ? v as Record<string, unknown> : undefined,
  /** An array of exactly `count` values (a tuple), or of any length. */
  array: (v: unknown, count?: number): unknown[] | undefined =>
    Array.isArray(v) && (count === undefined || v.length === count) ? v : undefined,
  /** Every element or nothing: one that does not read fails the list. */
  list: <T>(v: unknown, each: (v: unknown) => T | undefined): T[] | undefined => {
    if (!Array.isArray(v)) return undefined
    const out: T[] = []
    for (const item of v) {
      const r = each(item)
      if (r === undefined) return undefined
      out.push(r)
    }
    return out
  },
  map: <T>(v: unknown, each: (v: unknown) => T | undefined): { [key: string]: T } | undefined => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) return undefined
    const out: { [key: string]: T } = {}
    for (const [k, item] of Object.entries(v)) {
      const r = each(item)
      if (r === undefined) return undefined
      out[k] = r
    }
    return out
  },
}

// ---- the contract's types ----

export interface QRScannerParams {}
const readQRScannerParams = (v: unknown): QRScannerParams | undefined => !wire.present(v) || wire.object(v) ? {} : undefined

// ---- QRScanner ----

/** The events of "qrScanner": what the half sends the app. */
export interface QRScannerEvents {
  /** One per decoded camera frame: the payload, or null for a frame with no readable code (it
   *  repeats while the user aims). The same code may be reported more than once. */
  scan(payload: { data: string | null }): void
}

/** The view "qrScanner".
 *
 *  What the half implements. A call returns its result, or a promise of it; it rejects by throwing. */
export interface QRScannerPlugin {
  /** The element the host mounts. The half fills it and follows its size itself. */
  readonly el: HTMLElement
  /** The instance goes (the world swapped): release the hardware. */
  destroy?(): void
}

export const QRScannerChannel = {
  /** What the halves register under. */
  name: "qrScanner",
  /** The contract's version: the highest `@since` of its members. */
  version: 1,
} as const

/** Register the view: `make` builds one instance from its params, in the document it is handed. */
export const registerQRScanner = (host: PluginHost, make: (params: QRScannerParams, events: QRScannerEvents, doc: Document) => QRScannerPlugin): void => {
  host.registerView(QRScannerChannel.name, (params, channel, doc) => {
    const events: QRScannerEvents = {
      scan: (payload) => channel.emit("scan", payload),
    }
    const plugin = make(readQRScannerParams(params) ?? {}, events, doc)
    const call = async (method: string, args: unknown[]): Promise<unknown> => {
      switch (method) {
        default: throw new Error(`Unknown method: ${method}`)
      }
    }
    return { el: plugin.el, call, destroy: () => plugin.destroy?.() }
  }, QRScannerChannel.version)
}
