// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.
//
// The web half's side of the channel. This file imports nothing: a half depends on it, on the
// document it is handed and on the browser.

// ---- what the host hands a half ----

/** Where a half's events go. */
export interface PluginChannel { emit(event: string, data?: unknown): void }

/** The host, as a half needs it: a SHAPE — the host's own type is never imported. */
export interface PluginHost {
  // `version` = the contract version the half was generated from: what the app's `supports()` asks.
  registerService(name: string, factory: (params: unknown, channel: PluginChannel) => {
    call?(method: string, args: unknown[]): unknown, close?(): void,
  }, version: number): void
}

// The readers of the wire's values: undefined = absent, null, or not that type. On the web the wire
// carries the app's OWN values (the host is JavaScript like the app). What is read of the contract is
// built anew — a struct, a list, bytes — so what a half keeps is its own; a Json value alone is the
// app's object, as it is.
const wire = {
  present: (v: unknown): boolean => v !== undefined && v !== null,
  /** A number that is not finite is a null on the wire, as JSON has it. */
  f64: (v: unknown): number | undefined => typeof v === "number" && Number.isFinite(v) ? v : undefined,
  i32: (v: unknown): number | undefined =>
    typeof v === "number" && Number.isInteger(v) && v >= -2147483648 && v <= 2147483647 ? v : undefined,
  bool: (v: unknown): boolean | undefined => typeof v === "boolean" ? v : undefined,
  string: (v: unknown): string | undefined => typeof v === "string" ? v : undefined,
  /** Any JSON value, as it is; a null is a value here. */
  json: (v: unknown): any => v,
  /** A copy of the bytes. Told by its class name, not `instanceof`: the app's realm may not be the half's. */
  bytes: (v: unknown): Uint8Array | undefined =>
    Object.prototype.toString.call(v) === "[object Uint8Array]" ? (v as Uint8Array).slice() : undefined,
  object: (v: unknown): Record<string, unknown> | undefined =>
    typeof v === "object" && v !== null && !Array.isArray(v) ? v as Record<string, unknown> : undefined,
  /** An array of exactly `count` values (a tuple), or of any length. */
  array: (v: unknown, count?: number): unknown[] | undefined =>
    Array.isArray(v) && (count === undefined || v.length === count) ? v : undefined,
  /** Every element or nothing: one that does not read fails the list. */
  list: <T>(v: unknown, each: (v: unknown) => T | undefined): T[] | undefined => {
    if (!Array.isArray(v)) return undefined
    const out: T[] = []
    for (const item of v) {
      const r = each(item)
      if (r === undefined) return undefined
      out.push(r)
    }
    return out
  },
  map: <T>(v: unknown, each: (v: unknown) => T | undefined): { [key: string]: T } | undefined => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) return undefined
    const out: { [key: string]: T } = {}
    for (const [k, item] of Object.entries(v)) {
      const r = each(item)
      if (r === undefined) return undefined
      out[k] = r
    }
    return out
  },
}

// ---- the contract's types ----

export interface GeolocationParams {}
const readGeolocationParams = (v: unknown): GeolocationParams | undefined => !wire.present(v) || wire.object(v) ? {} : undefined

export interface GeoOptions {
  /** Prefer the precise (GPS) provider — slower first fix, more battery. Default false. */
  highAccuracy?: boolean
  /** getCurrent only: reject with "timeout" when no fix arrives in this many ms. */
  timeout?: number
}
const readGeoOptions = (v: unknown): GeoOptions | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: boolean | undefined = undefined
  if (wire.present(o.highAccuracy)) {
    const r = wire.bool(o.highAccuracy)
    if (r === undefined) return undefined
    f0 = r
  }
  let f1: number | undefined = undefined
  if (wire.present(o.timeout)) {
    const r = wire.f64(o.timeout)
    if (r === undefined) return undefined
    f1 = r
  }
  const out: GeoOptions = {}
  if (f0 !== undefined) out.highAccuracy = f0
  if (f1 !== undefined) out.timeout = f1
  return out
}

export interface GeoPosition {
  latitude: number
  longitude: number
  /** Horizontal accuracy radius, meters. */
  accuracy: number
  /** Meters above sea level; null when the provider does not know. */
  altitude: number | null
  /** Direction of travel, degrees clockwise from north; null when stationary or unknown. */
  heading: number | null
  /** Ground speed, m/s; null when unknown. */
  speed: number | null
  /** When the fix was taken, ms since the epoch. */
  timestamp: number
}

// ---- Geolocation ----

/** The codes the calls of "geolocation" reject with. */
export type GeolocationCode = "denied" | "unavailable" | "timeout"

/** What a call throws to reject with a code of the contract — the app's promise rejects with it
 *  as the message. Any other error is a message the contract has no code for. */
export class GeolocationError extends Error {
  constructor(readonly code: GeolocationCode) { super(code) }
}

/** The events of "geolocation": what the half sends the app. */
export interface GeolocationEvents {
  /** A fix of the live watch. */
  position(payload: GeoPosition): void
}

/** The service "geolocation".
 *
 *  What the half implements. A call returns its result, or a promise of it; it rejects by throwing. */
export interface GeolocationPlugin {
  /** One fix.
   *  Rejects with "denied" / "unavailable" / "timeout". */
  getCurrent(options?: GeoOptions): GeoPosition | Promise<GeoPosition>
  /** Start the session's watch; resolves once it is live (permission granted, provider started).
   *  A second call while watching resolves at once and keeps the first call's options.
   *  Rejects with "denied" / "unavailable". */
  startWatch(options?: GeoOptions): void | Promise<void>
  stopWatch(): void | Promise<void>
  /** The session closed (the app's close, the world's teardown): stop what it started. */
  close?(): void
}

export const GeolocationChannel = {
  /** What the halves register under. */
  name: "geolocation",
  /** The contract's version: the highest `@since` of its members. */
  version: 1,
} as const

/** Register the service: `make` builds one session from its params. It must be cheap — no prompt,
 *  no I/O: that belongs to the first call that needs it. */
export const registerGeolocation = (host: PluginHost, make: (params: GeolocationParams, events: GeolocationEvents) => GeolocationPlugin): void => {
  host.registerService(GeolocationChannel.name, (params, channel) => {
    const events: GeolocationEvents = {
      position: (payload) => channel.emit("position", payload),
    }
    const plugin = make(readGeolocationParams(params) ?? {}, events)
    const call = async (method: string, args: unknown[]): Promise<unknown> => {
      switch (method) {
        case "getCurrent": {
          let a0: GeoOptions | undefined = undefined
          if (wire.present(args[0])) {
            const r = readGeoOptions(args[0])
            if (r === undefined) throw new Error("bad arguments — Geolocation.getCurrent: options")
            a0 = r
          }
          return await plugin.getCurrent(a0)
        }
        case "startWatch": {
          let a0: GeoOptions | undefined = undefined
          if (wire.present(args[0])) {
            const r = readGeoOptions(args[0])
            if (r === undefined) throw new Error("bad arguments — Geolocation.startWatch: options")
            a0 = r
          }
          await plugin.startWatch(a0)
          return undefined
        }
        case "stopWatch": {
          await plugin.stopWatch()
          return undefined
        }
        default: throw new Error(`Unknown method: ${method}`)
      }
    }
    return { call, close: () => plugin.close?.() }
  }, GeolocationChannel.version)
}
