// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// qr-scanner: the view "qrScanner", contract version 1.

package io.letary.lecodes.plugins.qrscanner

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.NativeViews
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Wire
import org.json.JSONArray
import org.json.JSONObject

// ---- The contract's types ----

class QRScannerParams {
    companion object {
        internal fun fromWire(wire: Any?): QRScannerParams? = if (!Wire.present(wire) || Wire.obj(wire) != null) QRScannerParams() else null
    }
}

// ---- QRScanner ----

/** The events of "qrScanner": what the plugin sends the app. From the main thread. */
class QRScannerEvents(private val channel: PluginEmit) {
    /**
     * One per decoded camera frame: the payload, or null for a frame with no readable code (it
     * repeats while the user aims). The same code may be reported more than once.
     */
    fun scan(data: String? = null) {
        val o = JSONObject()
        o.put("data", (data ?: JSONObject.NULL))
        channel.emit("scan", o)
    }
}

/**
 * The view "qrScanner".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface QRScannerPlugin {
    /** The view the host mounts: fullscreen, or embedded among a screen's children. */
    val view: android.view.View

    /** The instance goes (the world swapped): release the hardware. */
    fun destroy() {}
}

object QRScannerChannel {
    /** What the halves register under. */
    const val NAME = "qrScanner"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the view: `make` builds one instance from its params. */
    fun register(engine: LecodesEngine, make: (params: QRScannerParams, events: QRScannerEvents) -> QRScannerPlugin) {
        engine.registerView(NAME, VERSION) { params, channel ->
            val plugin = make(QRScannerParams.fromWire(params) ?: QRScannerParams(), QRScannerEvents { event, data -> channel.emitValue(event, data) })
            NativeViews.Instance(plugin.view, onCall = { call -> QRScannerGlue.call(plugin, call.method, call.args, call) }, onDestroy = { plugin.destroy() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object QRScannerGlue {
    fun call(plugin: QRScannerPlugin, method: String, args: JSONArray, settle: ChannelSettle) {
        when (method) {
            else -> settle.reject("Unknown method: $method")
        }
    }
}
