// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.

package io.letary.lecodes.plugins.geolocation

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Services
import io.letary.lecodes.services.Wire
import org.json.JSONArray
import org.json.JSONObject

// ---- The contract's types ----

class GeolocationParams {
    companion object {
        internal fun fromWire(wire: Any?): GeolocationParams? = if (!Wire.present(wire) || Wire.obj(wire) != null) GeolocationParams() else null
    }
}

data class GeoOptions(
    /** Prefer the precise (GPS) provider — slower first fix, more battery. Default false. */
    val highAccuracy: Boolean? = null,
    /** getCurrent only: reject with "timeout" when no fix arrives in this many ms. */
    val timeout: Double? = null,
) {
    companion object {
        internal fun fromWire(wire: Any?): GeoOptions? {
            val o = Wire.obj(wire) ?: return null
            val highAccuracy = if (Wire.present(o.opt("highAccuracy"))) (Wire.bool(o.opt("highAccuracy")) ?: return null) else null
            val timeout = if (Wire.present(o.opt("timeout"))) (Wire.f64(o.opt("timeout")) ?: return null) else null
            return GeoOptions(highAccuracy = highAccuracy, timeout = timeout)
        }
    }
}

data class GeoPosition(
    val latitude: Double,
    val longitude: Double,
    /** Horizontal accuracy radius, meters. */
    val accuracy: Double,
    /** Meters above sea level; null when the provider does not know. */
    val altitude: Double? = null,
    /** Direction of travel, degrees clockwise from north; null when stationary or unknown. */
    val heading: Double? = null,
    /** Ground speed, m/s; null when unknown. */
    val speed: Double? = null,
    /** When the fix was taken, ms since the epoch. */
    val timestamp: Double,
) {
    internal val wire: Any
        get() {
            val o = JSONObject()
            o.put("latitude", Wire.number(latitude))
            o.put("longitude", Wire.number(longitude))
            o.put("accuracy", Wire.number(accuracy))
            o.put("altitude", (altitude?.let { v0 -> Wire.number(v0) } ?: JSONObject.NULL))
            o.put("heading", (heading?.let { v0 -> Wire.number(v0) } ?: JSONObject.NULL))
            o.put("speed", (speed?.let { v0 -> Wire.number(v0) } ?: JSONObject.NULL))
            o.put("timestamp", Wire.number(timestamp))
            return o
        }
}

// ---- Geolocation ----

/** The codes the calls of "geolocation" reject with. */
enum class GeolocationCode(override val code: String) : PluginCode {
    DENIED("denied"),
    UNAVAILABLE("unavailable"),
    TIMEOUT("timeout"),
}

/** The events of "geolocation": what the plugin sends the app. Any thread. */
class GeolocationEvents(private val channel: PluginEmit) {
    /** A fix of the live watch. */
    fun position(payload: GeoPosition) = channel.emit("position", Wire.text(payload.wire))
}

/**
 * The service "geolocation".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface GeolocationPlugin {
    /**
     * One fix.
     * Rejects with DENIED / UNAVAILABLE / TIMEOUT.
     */
    fun getCurrent(options: GeoOptions?, reply: Reply<GeoPosition, GeolocationCode>)

    /**
     * Start the session's watch; resolves once it is live (permission granted, provider started).
     * A second call while watching resolves at once and keeps the first call's options.
     * Rejects with DENIED / UNAVAILABLE.
     */
    fun startWatch(options: GeoOptions?, reply: Reply<Unit, GeolocationCode>)

    fun stopWatch(reply: Reply<Unit, GeolocationCode>)

    /** The session closed (the app's close, the world's teardown): stop what it started. */
    fun close() {}
}

object GeolocationChannel {
    /** What the halves register under. */
    const val NAME = "geolocation"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the service: `make` builds one session from its params. It must be cheap — no
     *  prompt, no I/O: that belongs to the first call that needs it. */
    fun register(engine: LecodesEngine, make: (params: GeolocationParams, events: GeolocationEvents) -> GeolocationPlugin) {
        engine.registerService(NAME) { params, channel ->
            val plugin = make(GeolocationParams.fromWire(params) ?: GeolocationParams(), GeolocationEvents { event, data -> channel.emit(event, data) })
            Services.Instance(onCall = { call -> GeolocationGlue.call(plugin, call.method, call.args, call) }, onClose = { plugin.close() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object GeolocationGlue {
    fun call(plugin: GeolocationPlugin, method: String, args: JSONArray, settle: ChannelSettle) {
        when (method) {
            "getCurrent" -> {
                val a0 = args.opt(0)
                val options = if (Wire.present(a0)) (GeoOptions.fromWire(a0) ?: return settle.reject("bad arguments — Geolocation.getCurrent: options")) else null
                plugin.getCurrent(options, Reply<GeoPosition, GeolocationCode>(settle) { v -> v.wire })
            }
            "startWatch" -> {
                val a0 = args.opt(0)
                val options = if (Wire.present(a0)) (GeoOptions.fromWire(a0) ?: return settle.reject("bad arguments — Geolocation.startWatch: options")) else null
                plugin.startWatch(options, Reply<Unit, GeolocationCode>(settle) { null })
            }
            "stopWatch" -> {
                plugin.stopWatch(Reply<Unit, GeolocationCode>(settle) { null })
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
