// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// geolocation: the service "geolocation", contract version 1.

package io.letary.lecodes.plugins.geolocation

import io.letary.lecodes.LecodesEngine
import io.letary.lecodes.services.ChannelSettle
import io.letary.lecodes.services.PluginCode
import io.letary.lecodes.services.PluginEmit
import io.letary.lecodes.services.Reply
import io.letary.lecodes.services.Services
import io.letary.lecodes.services.Wire
import io.letary.lecodes.core.PackedReader
import io.letary.lecodes.core.PackedWriter

// ---- The contract's types ----

class GeolocationParams {
    companion object {
        internal fun read(r: PackedReader): GeolocationParams? {
            if (r.isNull()) return GeolocationParams()
            if (r.beginObject() < 0) return null
            return GeolocationParams()
        }
    }
}

data class GeoOptions(
    /** Prefer the precise (GPS) provider — slower first fix, more battery. Default false. */
    val highAccuracy: Boolean? = null,
    /** getCurrent only: reject with "timeout" when no fix arrives in this many ms. */
    val timeout: Double? = null,
) {
    companion object {
        internal fun read(r: PackedReader): GeoOptions? {
            val n = r.beginObject()
            if (n < 0) return null
            var m0: Boolean? = null
            var m1: Double? = null
            repeat(n) {
                when (r.key()) {
                    "highAccuracy" -> if (r.isNull()) r.skip() else m0 = r.bool() ?: return null
                    "timeout" -> if (r.isNull()) r.skip() else m1 = r.f64() ?: return null
                    else -> r.skip()
                }
            }
            return GeoOptions(highAccuracy = m0, timeout = m1)
        }
    }
}

data class GeoPosition(
    val latitude: Double,
    val longitude: Double,
    /** Horizontal accuracy radius, meters. */
    val accuracy: Double,
    /** Meters above sea level; null when the provider does not know. */
    val altitude: Double? = null,
    /** Direction of travel, degrees clockwise from north; null when stationary or unknown. */
    val heading: Double? = null,
    /** Ground speed, m/s; null when unknown. */
    val speed: Double? = null,
    /** When the fix was taken, ms since the epoch. */
    val timestamp: Double,
) {
    internal fun write(w: PackedWriter) {
        w.beginObject()
        w.key("latitude"); w.f64(this.latitude)
        w.key("longitude"); w.f64(this.longitude)
        w.key("accuracy"); w.f64(this.accuracy)
        w.key("altitude")
        this.altitude.let { v0 -> if (v0 != null) w.f64(v0) else w.nil() }
        w.key("heading")
        this.heading.let { v0 -> if (v0 != null) w.f64(v0) else w.nil() }
        w.key("speed")
        this.speed.let { v0 -> if (v0 != null) w.f64(v0) else w.nil() }
        w.key("timestamp"); w.f64(this.timestamp)
        w.end()
    }
}

// ---- Geolocation ----

/** The codes the calls of "geolocation" reject with. */
enum class GeolocationCode(override val code: String) : PluginCode {
    DENIED("denied"),
    UNAVAILABLE("unavailable"),
    TIMEOUT("timeout"),
}

/** The events of "geolocation": what the plugin sends the app. Any thread. */
class GeolocationEvents(private val channel: PluginEmit) {
    /** A fix of the live watch. */
    fun position(payload: GeoPosition) {
        val w = PackedWriter()
        payload.write(w)
        channel.emit("position", w.bytes())
    }
}

/**
 * The service "geolocation".
 *
 * What the plugin implements. A call arrives on the main thread; its reply is settled exactly
 * once, now or later.
 */
interface GeolocationPlugin {
    /**
     * One fix.
     * Rejects with DENIED / UNAVAILABLE / TIMEOUT.
     */
    fun getCurrent(options: GeoOptions?, reply: Reply<GeoPosition, GeolocationCode>)

    /**
     * Start the session's watch; resolves once it is live (permission granted, provider started).
     * A second call while watching resolves at once and keeps the first call's options.
     * Rejects with DENIED / UNAVAILABLE.
     */
    fun startWatch(options: GeoOptions?, reply: Reply<Unit, GeolocationCode>)

    fun stopWatch(reply: Reply<Unit, GeolocationCode>)

    /** The session closed (the app's close, the world's teardown): stop what it started. */
    fun close() {}
}

object GeolocationChannel {
    /** What the halves register under. */
    const val NAME = "geolocation"

    /** The contract's version: the highest `@since` of its members. */
    const val VERSION = 1

    /** Register the service: `make` builds one session from its params. It must be cheap — no
     *  prompt, no I/O: that belongs to the first call that needs it. */
    fun register(engine: LecodesEngine, make: (params: GeolocationParams, events: GeolocationEvents) -> GeolocationPlugin) {
        engine.registerService(NAME, VERSION) { params, channel ->
            val plugin = make(GeolocationParams.read(Wire.reader(params)) ?: GeolocationParams(), GeolocationEvents { event, packed -> channel.emitPacked(event, packed) })
            Services.Instance(onCall = { call -> GeolocationGlue.call(plugin, call.method, call.reader(), call) }, onClose = { plugin.close() })
        }
    }
}

/** Reads a call off the wire and hands it to the plugin; a malformed call never reaches it. */
internal object GeolocationGlue {
    fun call(plugin: GeolocationPlugin, method: String, r: PackedReader, settle: ChannelSettle) {
        val n = r.beginArray()   // the arguments, in their order
        when (method) {
            "getCurrent" -> {
                val a0 = if (0 < n && !r.isNull()) (GeoOptions.read(r) ?: return settle.reject("bad arguments — Geolocation.getCurrent: options")) else { if (0 < n) r.skip(); null }
                plugin.getCurrent(a0, Reply<GeoPosition, GeolocationCode>(settle) { v, w -> v.write(w) })
            }
            "startWatch" -> {
                val a0 = if (0 < n && !r.isNull()) (GeoOptions.read(r) ?: return settle.reject("bad arguments — Geolocation.startWatch: options")) else { if (0 < n) r.skip(); null }
                plugin.startWatch(a0, Reply<Unit, GeolocationCode>(settle, null))
            }
            "stopWatch" -> {
                plugin.stopWatch(Reply<Unit, GeolocationCode>(settle, null))
            }
            else -> settle.reject("Unknown method: $method")
        }
    }
}
