// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// push: the service "push", contract version 1.

import Foundation
import LeCodes

// MARK: - The contract's types

public struct PushParams {
    public init() {}

    init?(wire: Any?) {
        guard wire == nil || wire is NSNull || Wire.object(wire) != nil else { return nil }
    }
}

public enum PushStatusPermission: String {
    case granted
    case denied
    case prompt
}

public struct PushStatus {
    /// The OS permission of the host app. "prompt" = not asked yet.
    public var permission: PushStatusPermission
    /// Whether this device holds a registration (an address) for this app.
    public var registered: Bool

    public init(permission: PushStatusPermission, registered: Bool) {
        self.permission = permission
        self.registered = registered
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["permission"] = permission.rawValue
        o["registered"] = registered
        return o
    }
}

public struct PushRegisterOptions {
    /// The app's OWN user id. Client-asserted and unverified. The registration reflects the latest
    /// call: registering without it clears it.
    public var user: String?

    public init(user: String? = nil) {
        self.user = user
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["user"]) {
            guard let user = Wire.string(o["user"]) else { return nil }
            self.user = user
        } else { self.user = nil }
    }
}

public struct PushRegistration {
    public var address: String

    public init(address: String) {
        self.address = address
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["address"] = address
        return o
    }
}

/// A delivered notification, as the app sees it.
public struct PushPayload {
    public var title: String
    public var body: String?
    /// A deep link — it also rides the app's own link path (`app.launchUrl`, the "url" event).
    public var url: String?
    /// The developer's own JSON object, ≤ 2 KB serialized.
    public var data: [String: Any]?
    public var badge: Int32?

    public init(title: String, body: String? = nil, url: String? = nil, data: [String: Any]? = nil, badge: Int32? = nil) {
        self.title = title
        self.body = body
        self.url = url
        self.data = data
        self.badge = badge
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["title"] = title
        if let v = body { o["body"] = v }
        if let v = url { o["url"] = v }
        if let v = data { o["data"] = v.mapValues({ v1 -> Any in v1 }) }
        if let v = badge { o["badge"] = v }
        return o
    }
}

// MARK: - Push

/// The codes the calls of "push" reject with.
public enum PushCode: String, PluginCode {
    case denied
    case unavailable
}

/// The events of "push": what the plugin sends the app. Any thread.
public struct PushEvents {
    let channel: ServiceChannel

    /// Arrived while this app was in the foreground (the host shows no banner).
    public func message(_ payload: PushPayload) { channel.emit("message", payload.wire) }

    /// Tapped while the world was alive.
    public func tap(_ payload: PushPayload) { channel.emit("tap", payload.wire) }
}

/// The service "push".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol PushPlugin: AnyObject {
    /// Permission + registration state. Never prompts.
    func getStatus(_ reply: Reply<PushStatus, PushCode>)
    /// Ask for the permission (the first time) and register this device. Idempotent.
    /// Rejects with .denied / .unavailable.
    func register(_ options: PushRegisterOptions?, _ reply: Reply<PushRegistration, PushCode>)
    /// Remove this device's registration.
    /// Rejects with .unavailable.
    func unregister(_ reply: Reply<Void, PushCode>)
    /// The notification that cold-started this world, or null. Stable across calls.
    func getLaunch(_ reply: Reply<PushPayload?, PushCode>)

    /// The session closed (the app's close, the world's teardown): stop what it started.
    func close()
}

public extension PushPlugin {
    func close() {}
}

public enum PushChannel {
    /// What the halves register under.
    public static let name = "push"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the service: `make` builds one session from its params. It must be cheap — no prompt,
    /// no I/O: that belongs to the first call that needs it.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (PushParams, PushEvents) -> PushPlugin) {
        engine.registerService(name) { params, channel in
            PushGlue(make(PushParams(wire: params) ?? PushParams(), PushEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class PushGlue: ServiceInstance {
    private let plugin: PushPlugin

    init(_ plugin: PushPlugin) { self.plugin = plugin }

    func call(_ method: String, _ args: [Any], _ settle: ChannelSettle) {
        switch method {
        case "getStatus":
            plugin.getStatus(Reply<PushStatus, PushCode>(settle) { v in v.wire })
        case "register":
            let a0: Any? = args.count > 0 ? args[0] : nil
            var options: PushRegisterOptions? = nil
            if Wire.present(a0) {
                guard let v = PushRegisterOptions(wire: a0) else { return settle.reject("bad arguments — Push.register: options") }
                options = v
            }
            plugin.register(options, Reply<PushRegistration, PushCode>(settle) { v in v.wire })
        case "unregister":
            plugin.unregister(Reply<Void, PushCode>(settle) { _ in nil })
        case "getLaunch":
            plugin.getLaunch(Reply<PushPayload?, PushCode>(settle) { v in v.map({ v1 -> Any in v1.wire }) })
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func close() { plugin.close() }
}
