// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// push: the service "push", contract version 1.

import Foundation
import LeCodes

// MARK: - The contract's types

public struct PushParams {
    public init() {}

    init?(wire: WireIn) {
        guard !wire.isPresent || wire.isObject else { return nil }
    }
}

public enum PushStatusPermission: String {
    case granted
    case denied
    case prompt
}

public struct PushStatus {
    /// The OS permission of the host app. "prompt" = not asked yet.
    public var permission: PushStatusPermission
    /// Whether this device holds a registration (an address) for this app.
    public var registered: Bool

    public init(permission: PushStatusPermission, registered: Bool) {
        self.permission = permission
        self.registered = registered
    }

    func write(to w: WireOut) {
        w.beginObject(2)
        w.key("permission"); w.string(self.permission.rawValue)
        w.key("registered"); w.bool(self.registered)
        w.end()
    }
}

public struct PushRegisterOptions {
    /// The app's OWN user id. Client-asserted and unverified. The registration reflects the latest
    /// call: registering without it clears it.
    public var user: String?

    public init(user: String? = nil) {
        self.user = user
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["user", 0]
        if m0.isPresent {
            guard let v = m0.string else { return nil }
            self.user = v
        } else {
            self.user = nil
        }
    }
}

public struct PushRegistration {
    public var address: String

    public init(address: String) {
        self.address = address
    }

    func write(to w: WireOut) {
        w.beginObject(1)
        w.key("address"); w.string(self.address)
        w.end()
    }
}

/// A delivered notification, as the app sees it.
public struct PushPayload {
    public var title: String
    public var body: String?
    /// A deep link — it also rides the app's own link path (`app.launchUrl`, the "url" event).
    public var url: String?
    /// The developer's own JSON object, ≤ 2 KB serialized.
    public var data: [String: Any]?
    public var badge: Int32?

    public init(title: String, body: String? = nil, url: String? = nil, data: [String: Any]? = nil, badge: Int32? = nil) {
        self.title = title
        self.body = body
        self.url = url
        self.data = data
        self.badge = badge
    }

    func write(to w: WireOut) {
        w.beginObject(5)
        w.key("title"); w.string(self.title)
        if let v = self.body { w.key("body"); w.string(v) }
        if let v = self.url { w.key("url"); w.string(v) }
        if let v = self.data {
            w.key("data")
            w.beginObject(v.count)
            for (k1, v1) in v {
                w.name(k1)
                w.json(v1)
            }
            w.end()
        }
        if let v = self.badge { w.key("badge"); w.i32(v) }
        w.end()
    }
}

// MARK: - Push

/// The codes the calls of "push" reject with.
public enum PushCode: String, PluginCode {
    case denied
    case unavailable
}

/// The events of "push": what the plugin sends the app. Any thread.
public struct PushEvents {
    let channel: ServiceChannel

    /// Arrived while this app was in the foreground (the host shows no banner).
    public func message(_ payload: PushPayload) {
        channel.emit("message") { w in payload.write(to: w) }
    }

    /// Tapped while the world was alive.
    public func tap(_ payload: PushPayload) {
        channel.emit("tap") { w in payload.write(to: w) }
    }
}

/// The service "push".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol PushPlugin: AnyObject {
    /// Permission + registration state. Never prompts.
    func getStatus(_ reply: Reply<PushStatus, PushCode>)
    /// Ask for the permission (the first time) and register this device. Idempotent.
    /// Rejects with .denied / .unavailable.
    func register(_ options: PushRegisterOptions?, _ reply: Reply<PushRegistration, PushCode>)
    /// Remove this device's registration.
    /// Rejects with .unavailable.
    func unregister(_ reply: Reply<Void, PushCode>)
    /// The notification that cold-started this world, or null. Stable across calls.
    func getLaunch(_ reply: Reply<PushPayload?, PushCode>)

    /// The session closed (the app's close, the world's teardown): stop what it started.
    func close()
}

public extension PushPlugin {
    func close() {}
}

public enum PushChannel {
    /// What the halves register under.
    public static let name = "push"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the service: `make` builds one session from its params. It must be cheap — no prompt,
    /// no I/O: that belongs to the first call that needs it.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (PushParams, PushEvents) -> PushPlugin) {
        engine.registerService(name, version: Int32(version)) { params, channel in
            PushGlue(make(WireIn.of(params, { PushParams(wire: $0) }) ?? PushParams(), PushEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class PushGlue: WireServiceInstance {
    private let plugin: PushPlugin

    init(_ plugin: PushPlugin) { self.plugin = plugin }

    func call(_ method: String, wire args: WireIn, _ settle: ChannelSettle) {
        switch method {
        case "getStatus":
            plugin.getStatus(Reply<PushStatus, PushCode>(settle) { v, w in v.write(to: w) })
        case "register":
            let w0 = args[0]
            var a0: PushRegisterOptions? = nil
            if w0.isPresent {
                guard let v = PushRegisterOptions(wire: w0) else { return settle.reject("bad arguments — Push.register: options") }
                a0 = v
            }
            plugin.register(a0, Reply<PushRegistration, PushCode>(settle) { v, w in v.write(to: w) })
        case "unregister":
            plugin.unregister(Reply<Void, PushCode>(settle))
        case "getLaunch":
            plugin.getLaunch(Reply<PushPayload?, PushCode>(settle) { v, w in if let v1 = v { v1.write(to: w) } })
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func close() { plugin.close() }
}
