// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// camera: the view "camera", contract version 1.
//
// The web half's side of the channel. This file imports nothing: a half depends on it, on the
// document it is handed and on the browser.

// ---- what the host hands a half ----

/** Where a half's events go. */
export interface PluginChannel { emit(event: string, data?: unknown): void }

/** The host, as a half needs it: a SHAPE — the host's own type is never imported. */
export interface PluginHost {
  registerView(name: string, factory: (params: unknown, channel: PluginChannel, doc: Document) => {
    el: HTMLElement, call?(method: string, args: unknown[]): unknown, destroy?(): void,
  }): void
  /** Store bytes in the host's buffer table: the handle a File crosses as. */
  putBuffer(bytes: ArrayBuffer): number
}

/** Bytes a half hands to the app as a `File`: they go into the host's buffer table, the app gets
 *  the handle (a texture source, an upload, a share). */
export interface PluginFile { data: ArrayBuffer | Uint8Array, name: string }

const writeFile = (host: PluginHost, file: PluginFile): unknown => {
  const bytes = file.data instanceof Uint8Array ? file.data.slice().buffer : file.data
  return { systemId: host.putBuffer(bytes), name: file.name, size: bytes.byteLength }
}

// The readers of the wire's values: undefined = absent, null, or not that type.
const wire = {
  present: (v: unknown): boolean => v !== undefined && v !== null,
  f64: (v: unknown): number | undefined => typeof v === "number" ? v : undefined,
  i32: (v: unknown): number | undefined =>
    typeof v === "number" && Number.isInteger(v) && v >= -2147483648 && v <= 2147483647 ? v : undefined,
  bool: (v: unknown): boolean | undefined => typeof v === "boolean" ? v : undefined,
  string: (v: unknown): string | undefined => typeof v === "string" ? v : undefined,
  /** Any JSON value, as it is; a null is a value here. */
  json: (v: unknown): any => v,
  object: (v: unknown): Record<string, unknown> | undefined =>
    typeof v === "object" && v !== null && !Array.isArray(v) ? v as Record<string, unknown> : undefined,
  /** An array of exactly `count` values (a tuple), or of any length. */
  array: (v: unknown, count?: number): unknown[] | undefined =>
    Array.isArray(v) && (count === undefined || v.length === count) ? v : undefined,
  /** Every element or nothing: one that does not read fails the list. */
  list: <T>(v: unknown, each: (v: unknown) => T | undefined): T[] | undefined => {
    if (!Array.isArray(v)) return undefined
    const out: T[] = []
    for (const item of v) {
      const r = each(item)
      if (r === undefined) return undefined
      out.push(r)
    }
    return out
  },
  map: <T>(v: unknown, each: (v: unknown) => T | undefined): { [key: string]: T } | undefined => {
    if (typeof v !== "object" || v === null || Array.isArray(v)) return undefined
    const out: { [key: string]: T } = {}
    for (const [k, item] of Object.entries(v)) {
      const r = each(item)
      if (r === undefined) return undefined
      out[k] = r
    }
    return out
  },
}

// ---- the contract's types ----

export type Facing = "front" | "back"
const readFacing = (v: unknown): Facing | undefined =>
  v === "front" || v === "back" ? v : undefined

export interface CameraParams {
  /** Default "back". */
  facingMode?: Facing
}
const readCameraParams = (v: unknown): CameraParams | undefined => {
  const o = wire.object(v)
  if (!o) return undefined
  let f0: Facing | undefined = undefined
  if (wire.present(o.facingMode)) {
    const r = readFacing(o.facingMode)
    if (r === undefined) return undefined
    f0 = r
  }
  const out: CameraParams = {}
  if (f0 !== undefined) out.facingMode = f0
  return out
}

// ---- CameraView ----

/** The codes the calls of "camera" reject with. */
export type CameraViewCode = "failed"

/** What a call throws to reject with a code of the contract — the app's promise rejects with it
 *  as the message. Any other error is a message the contract has no code for. */
export class CameraViewError extends Error {
  constructor(readonly code: CameraViewCode) { super(code) }
}

/** The events of "camera": what the half sends the app. */
export interface CameraViewEvents {
  /** The preview could not start or stopped (no camera, the stream was refused). */
  error(payload: { message: string }): void
}

/** The view "camera".
 *
 *  What the half implements. A call returns its result, or a promise of it; it rejects by throwing. */
export interface CameraViewPlugin {
  /** The element the host mounts. The half fills it and follows its size itself. */
  readonly el: HTMLElement
  /** Capture a still frame as a JPEG.
   *  Rejects with "failed". */
  takePhoto(): PluginFile | Promise<PluginFile>
  /** Switch the camera while the preview is live. */
  setFacingMode(mode: Facing): void | Promise<void>
  /** The instance goes (the world swapped): release the hardware. */
  destroy?(): void
}

export const CameraViewChannel = {
  /** What the halves register under. */
  name: "camera",
  /** The contract's version: the highest `@since` of its members. */
  version: 1,
} as const

/** Register the view: `make` builds one instance from its params, in the document it is handed. */
export const registerCameraView = (host: PluginHost, make: (params: CameraParams, events: CameraViewEvents, doc: Document) => CameraViewPlugin): void => {
  host.registerView(CameraViewChannel.name, (params, channel, doc) => {
    const events: CameraViewEvents = {
      error: (payload) => channel.emit("error", payload),
    }
    const plugin = make(readCameraParams(params) ?? {}, events, doc)
    const call = async (method: string, args: unknown[]): Promise<unknown> => {
      switch (method) {
        case "takePhoto": {
          const r = await plugin.takePhoto()
          return writeFile(host, r)
        }
        case "setFacingMode": {
          const a0 = readFacing(args[0])
          if (a0 === undefined) throw new Error("bad arguments — CameraView.setFacingMode: mode")
          await plugin.setFacingMode(a0)
          return undefined
        }
        default: throw new Error(`Unknown method: ${method}`)
      }
    }
    return { el: plugin.el, call, destroy: () => plugin.destroy?.() }
  })
}
