// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.

import Foundation
import UIKit
import LeCodes

// MARK: - The contract's types

public struct MapParams {
    /// A style URL the map fetches itself.
    public var style: String?
    /// A style as JSON text; wins over `style`. It has no base url: every url INSIDE it (sources,
    /// sprite, glyphs) must be absolute.
    public var styleJson: String?
    public var center: (Double, Double)?
    /// Default 12 with a center.
    public var zoom: Double?
    public var minZoom: Double?
    public var maxZoom: Double?
    /// Degrees clockwise from north.
    public var bearing: Double?
    /// Degrees from the vertical.
    public var pitch: Double?
    /// The two-finger rotate gesture. Default true.
    public var rotate: Bool?
    /// The two-finger tilt gesture. Default false.
    public var tilt: Bool?

    public init(style: String? = nil, styleJson: String? = nil, center: (Double, Double)? = nil, zoom: Double? = nil, minZoom: Double? = nil, maxZoom: Double? = nil, bearing: Double? = nil, pitch: Double? = nil, rotate: Bool? = nil, tilt: Bool? = nil) {
        self.style = style
        self.styleJson = styleJson
        self.center = center
        self.zoom = zoom
        self.minZoom = minZoom
        self.maxZoom = maxZoom
        self.bearing = bearing
        self.pitch = pitch
        self.rotate = rotate
        self.tilt = tilt
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["style", 0]
        if m0.isPresent {
            guard let v = m0.string else { return nil }
            self.style = v
        } else {
            self.style = nil
        }
        let m1 = wire["styleJson", 1]
        if m1.isPresent {
            guard let v = m1.string else { return nil }
            self.styleJson = v
        } else {
            self.styleJson = nil
        }
        let m2 = wire["center", 2]
        if m2.isPresent {
            guard let v = m2.tuple(2).flatMap({ v0 -> (Double, Double)? in
                guard let v0_0 = v0[0].f64, let v0_1 = v0[1].f64 else { return nil }
                return (v0_0, v0_1)
            }) else { return nil }
            self.center = v
        } else {
            self.center = nil
        }
        let m3 = wire["zoom", 3]
        if m3.isPresent {
            guard let v = m3.f64 else { return nil }
            self.zoom = v
        } else {
            self.zoom = nil
        }
        let m4 = wire["minZoom", 4]
        if m4.isPresent {
            guard let v = m4.f64 else { return nil }
            self.minZoom = v
        } else {
            self.minZoom = nil
        }
        let m5 = wire["maxZoom", 5]
        if m5.isPresent {
            guard let v = m5.f64 else { return nil }
            self.maxZoom = v
        } else {
            self.maxZoom = nil
        }
        let m6 = wire["bearing", 6]
        if m6.isPresent {
            guard let v = m6.f64 else { return nil }
            self.bearing = v
        } else {
            self.bearing = nil
        }
        let m7 = wire["pitch", 7]
        if m7.isPresent {
            guard let v = m7.f64 else { return nil }
            self.pitch = v
        } else {
            self.pitch = nil
        }
        let m8 = wire["rotate", 8]
        if m8.isPresent {
            guard let v = m8.bool else { return nil }
            self.rotate = v
        } else {
            self.rotate = nil
        }
        let m9 = wire["tilt", 9]
        if m9.isPresent {
            guard let v = m9.bool else { return nil }
            self.tilt = v
        } else {
            self.tilt = nil
        }
    }
}

public enum MapLayerKind: String {
    case markers
    case line

    init?(wire: WireIn) {
        guard let raw = wire.string, let value = MapLayerKind(rawValue: raw) else { return nil }
        self = value
    }
}

/// The keys of both kinds; a half reads the ones of the kind it is asked for.
public struct MapLayerOptions {
    /// markers: group nearby markers (a cluster tap zooms in). Default false.
    public var cluster: Bool?
    /// markers: px. Default 50.
    public var clusterRadius: Double?
    /// markers: the zoom at which clusters stop forming.
    public var clusterMaxZoom: Double?
    /// line.
    public var color: String?
    /// line: px. Default 4.
    public var width: Double?
    /// line: 0–1. Default 1.
    public var opacity: Double?

    public init(cluster: Bool? = nil, clusterRadius: Double? = nil, clusterMaxZoom: Double? = nil, color: String? = nil, width: Double? = nil, opacity: Double? = nil) {
        self.cluster = cluster
        self.clusterRadius = clusterRadius
        self.clusterMaxZoom = clusterMaxZoom
        self.color = color
        self.width = width
        self.opacity = opacity
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["cluster", 0]
        if m0.isPresent {
            guard let v = m0.bool else { return nil }
            self.cluster = v
        } else {
            self.cluster = nil
        }
        let m1 = wire["clusterRadius", 1]
        if m1.isPresent {
            guard let v = m1.f64 else { return nil }
            self.clusterRadius = v
        } else {
            self.clusterRadius = nil
        }
        let m2 = wire["clusterMaxZoom", 2]
        if m2.isPresent {
            guard let v = m2.f64 else { return nil }
            self.clusterMaxZoom = v
        } else {
            self.clusterMaxZoom = nil
        }
        let m3 = wire["color", 3]
        if m3.isPresent {
            guard let v = m3.string else { return nil }
            self.color = v
        } else {
            self.color = nil
        }
        let m4 = wire["width", 4]
        if m4.isPresent {
            guard let v = m4.f64 else { return nil }
            self.width = v
        } else {
            self.width = nil
        }
        let m5 = wire["opacity", 5]
        if m5.isPresent {
            guard let v = m5.f64 else { return nil }
            self.opacity = v
        } else {
            self.opacity = nil
        }
    }
}

public struct MapCameraMove {
    public var zoom: Double?
    public var bearing: Double?
    public var pitch: Double?
    /// flyTo only: ms. Default 600.
    public var duration: Double?

    public init(zoom: Double? = nil, bearing: Double? = nil, pitch: Double? = nil, duration: Double? = nil) {
        self.zoom = zoom
        self.bearing = bearing
        self.pitch = pitch
        self.duration = duration
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["zoom", 0]
        if m0.isPresent {
            guard let v = m0.f64 else { return nil }
            self.zoom = v
        } else {
            self.zoom = nil
        }
        let m1 = wire["bearing", 1]
        if m1.isPresent {
            guard let v = m1.f64 else { return nil }
            self.bearing = v
        } else {
            self.bearing = nil
        }
        let m2 = wire["pitch", 2]
        if m2.isPresent {
            guard let v = m2.f64 else { return nil }
            self.pitch = v
        } else {
            self.pitch = nil
        }
        let m3 = wire["duration", 3]
        if m3.isPresent {
            guard let v = m3.f64 else { return nil }
            self.duration = v
        } else {
            self.duration = nil
        }
    }
}

/// Px, or a share of the view's size as "NN%".
public enum MapInset {
    case number(Double)
    case string(String)

    init?(wire: WireIn) {
        if let v = wire.f64 {
            self = .number(v)
            return
        }
        if let v = wire.string {
            self = .string(v)
            return
        }
        return nil
    }
}

public struct MapPadding {
    public var top: MapInset?
    public var left: MapInset?
    public var bottom: MapInset?
    public var right: MapInset?

    public init(top: MapInset? = nil, left: MapInset? = nil, bottom: MapInset? = nil, right: MapInset? = nil) {
        self.top = top
        self.left = left
        self.bottom = bottom
        self.right = right
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["top", 0]
        if m0.isPresent {
            guard let v = MapInset(wire: m0) else { return nil }
            self.top = v
        } else {
            self.top = nil
        }
        let m1 = wire["left", 1]
        if m1.isPresent {
            guard let v = MapInset(wire: m1) else { return nil }
            self.left = v
        } else {
            self.left = nil
        }
        let m2 = wire["bottom", 2]
        if m2.isPresent {
            guard let v = MapInset(wire: m2) else { return nil }
            self.bottom = v
        } else {
            self.bottom = nil
        }
        let m3 = wire["right", 3]
        if m3.isPresent {
            guard let v = MapInset(wire: m3) else { return nil }
            self.right = v
        } else {
            self.right = nil
        }
    }
}

public enum MapFitOptionsPadding {
    case number(Double)
    case mapPadding(MapPadding)

    init?(wire: WireIn) {
        if let v = wire.f64 {
            self = .number(v)
            return
        }
        if let v = MapPadding(wire: wire) {
            self = .mapPadding(v)
            return
        }
        return nil
    }
}

public struct MapFitOptions {
    /// Around the points: px on every edge, or per edge. Added to the view padding.
    public var padding: MapFitOptionsPadding?
    /// Default: 16 for one point, none otherwise.
    public var maxZoom: Double?
    /// Default true.
    public var animate: Bool?

    public init(padding: MapFitOptionsPadding? = nil, maxZoom: Double? = nil, animate: Bool? = nil) {
        self.padding = padding
        self.maxZoom = maxZoom
        self.animate = animate
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["padding", 0]
        if m0.isPresent {
            guard let v = MapFitOptionsPadding(wire: m0) else { return nil }
            self.padding = v
        } else {
            self.padding = nil
        }
        let m1 = wire["maxZoom", 1]
        if m1.isPresent {
            guard let v = m1.f64 else { return nil }
            self.maxZoom = v
        } else {
            self.maxZoom = nil
        }
        let m2 = wire["animate", 2]
        if m2.isPresent {
            guard let v = m2.bool else { return nil }
            self.animate = v
        } else {
            self.animate = nil
        }
    }
}

public struct MapCamera {
    public var center: (Double, Double)
    public var zoom: Double
    public var bearing: Double
    public var pitch: Double

    public init(center: (Double, Double), zoom: Double, bearing: Double, pitch: Double) {
        self.center = center
        self.zoom = zoom
        self.bearing = bearing
        self.pitch = pitch
    }

    func write(to w: WireOut) {
        w.beginObject(4)
        w.key("center")
        w.beginArray(2)
        w.f64(self.center.0)
        w.f64(self.center.1)
        w.end()
        w.key("zoom"); w.f64(self.zoom)
        w.key("bearing"); w.f64(self.bearing)
        w.key("pitch"); w.f64(self.pitch)
        w.end()
    }
}

public struct MapUserLocationOptions {
    /// Meters — the halo around the dot.
    public var accuracy: Double?
    /// Degrees clockwise from north — the direction wedge; null hides it.
    public var heading: Double?

    public init(accuracy: Double? = nil, heading: Double? = nil) {
        self.accuracy = accuracy
        self.heading = heading
    }

    init?(wire: WireIn) {
        guard wire.isObject else { return nil }
        let m0 = wire["accuracy", 0]
        if m0.isPresent {
            guard let v = m0.f64 else { return nil }
            self.accuracy = v
        } else {
            self.accuracy = nil
        }
        let m1 = wire["heading", 1]
        if m1.isPresent {
            guard let v = m1.f64 else { return nil }
            self.heading = v
        } else {
            self.heading = nil
        }
    }
}

public enum MapFeatureId {
    case string(String)
    case number(Double)

    func write(to w: WireOut) {
        switch self {
        case .string(let v): w.string(v)
        case .number(let v): w.f64(v)
        }
    }
}

/// A feature of a managed source under a tap.
public struct MapFeature {
    /// The source's name — the layer's name in the app.
    public var source: String
    public var id: MapFeatureId?
    public var properties: [String: Any]

    public init(source: String, id: MapFeatureId? = nil, properties: [String: Any]) {
        self.source = source
        self.id = id
        self.properties = properties
    }

    func write(to w: WireOut) {
        w.beginObject(3)
        w.key("source"); w.string(self.source)
        w.key("id")
        if let v0 = self.id { v0.write(to: w) } else { w.null() }
        w.key("properties")
        w.beginObject(self.properties.count)
        for (k0, v0) in self.properties {
            w.name(k0)
            w.json(v0)
        }
        w.end()
        w.end()
    }
}

public struct MapTap {
    public var lngLat: (Double, Double)
    /// View-space point, logical px.
    public var point: (Double, Double)
    /// Absent for a tap that hit no feature of a managed source. A tap on a CLUSTER zooms in and
    /// sends no event.
    public var feature: MapFeature?

    public init(lngLat: (Double, Double), point: (Double, Double), feature: MapFeature? = nil) {
        self.lngLat = lngLat
        self.point = point
        self.feature = feature
    }

    func write(to w: WireOut) {
        w.beginObject(3)
        w.key("lngLat")
        w.beginArray(2)
        w.f64(self.lngLat.0)
        w.f64(self.lngLat.1)
        w.end()
        w.key("point")
        w.beginArray(2)
        w.f64(self.point.0)
        w.f64(self.point.1)
        w.end()
        if let v = self.feature { w.key("feature"); v.write(to: w) }
        w.end()
    }
}

// MARK: - MapView

/// The codes the calls of "map" reject with.
public enum MapViewCode: String, PluginCode {
    case notReady
    case noPoints
}

/// The events of "map": what the plugin sends the app. Any thread.
public struct MapViewEvents {
    let channel: NativeViewChannel

    /// The style loaded and the map takes calls. Fires again after every style reload.
    public func ready() { channel.emit("ready") }

    public func tap(_ payload: MapTap) {
        channel.emit("tap") { w in payload.write(to: w) }
    }

    /// The camera settled after a gesture or an animation.
    public func moveEnd(_ payload: MapCamera) {
        channel.emit("moveEnd") { w in payload.write(to: w) }
    }

    /// A problem that is never fatal: a style that would not load, a source out of reach.
    public func error(message: String) {
        self.channel.emit("error") { w in
            w.beginObject(1)
            w.key("message"); w.string(message)
            w.end()
        }
    }
}

/// The view "map".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol MapViewPlugin: AnyObject {
    /// The view the host mounts: fullscreen, or embedded among a screen's children.
    var view: UIView { get }

    /// Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
    /// layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
    /// Rejects with .notReady.
    func ensureLayer(_ source: String, _ kind: MapLayerKind, _ options: MapLayerOptions?, _ reply: Reply<Void, MapViewCode>)
    func removeLayer(_ source: String, _ reply: Reply<Void, MapViewCode>)
    /// Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
    /// Rejects with .notReady.
    func setData(_ source: String, _ geojson: Any, _ reply: Reply<Void, MapViewCode>)
    func flyTo(_ center: (Double, Double), _ options: MapCameraMove?, _ reply: Reply<Void, MapViewCode>)
    func jumpTo(_ center: (Double, Double), _ options: MapCameraMove?, _ reply: Reply<Void, MapViewCode>)
    /// Fit the camera to the points.
    /// Rejects with .noPoints.
    func fitPoints(_ points: [(Double, Double)], _ options: MapFitOptions?, _ reply: Reply<Void, MapViewCode>)
    /// The part of the view covered by the app's UI; camera moves center inside the rest.
    func setPadding(_ padding: MapPadding, _ reply: Reply<Void, MapViewCode>)
    /// Rejects with .notReady.
    func getCamera(_ reply: Reply<MapCamera, MapViewCode>)
    /// Move the user puck; null hides it.
    func setUserLocation(_ lngLat: (Double, Double)?, _ options: MapUserLocationOptions?, _ reply: Reply<Void, MapViewCode>)

    /// The instance goes (the world swapped): release the hardware.
    func destroy()
}

public extension MapViewPlugin {
    func destroy() {}
}

public enum MapViewChannel {
    /// What the halves register under.
    public static let name = "map"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the view: `make` builds one instance from its params.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (MapParams, MapViewEvents) -> MapViewPlugin) {
        engine.registerView(name, version: Int32(version)) { params, channel in
            MapViewGlue(make(WireIn.of(params, { MapParams(wire: $0) }) ?? MapParams(), MapViewEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class MapViewGlue: WireNativeViewInstance {
    private let plugin: MapViewPlugin

    init(_ plugin: MapViewPlugin) { self.plugin = plugin }

    var view: UIView { plugin.view }

    func call(_ method: String, wire args: WireIn, _ settle: ChannelSettle) {
        switch method {
        case "ensureLayer":
            guard let a0 = args[0].string else { return settle.reject("bad arguments — MapView.ensureLayer: source") }
            guard let a1 = MapLayerKind(wire: args[1]) else { return settle.reject("bad arguments — MapView.ensureLayer: kind") }
            let w2 = args[2]
            var a2: MapLayerOptions? = nil
            if w2.isPresent {
                guard let v = MapLayerOptions(wire: w2) else { return settle.reject("bad arguments — MapView.ensureLayer: options") }
                a2 = v
            }
            plugin.ensureLayer(a0, a1, a2, Reply<Void, MapViewCode>(settle))
        case "removeLayer":
            guard let a0 = args[0].string else { return settle.reject("bad arguments — MapView.removeLayer: source") }
            plugin.removeLayer(a0, Reply<Void, MapViewCode>(settle))
        case "setData":
            guard let a0 = args[0].string else { return settle.reject("bad arguments — MapView.setData: source") }
            guard let a1 = args[1].json else { return settle.reject("bad arguments — MapView.setData: geojson") }
            plugin.setData(a0, a1, Reply<Void, MapViewCode>(settle))
        case "flyTo":
            guard let a0 = args[0].tuple(2).flatMap({ v0 -> (Double, Double)? in
                guard let v0_0 = v0[0].f64, let v0_1 = v0[1].f64 else { return nil }
                return (v0_0, v0_1)
            }) else { return settle.reject("bad arguments — MapView.flyTo: center") }
            let w1 = args[1]
            var a1: MapCameraMove? = nil
            if w1.isPresent {
                guard let v = MapCameraMove(wire: w1) else { return settle.reject("bad arguments — MapView.flyTo: options") }
                a1 = v
            }
            plugin.flyTo(a0, a1, Reply<Void, MapViewCode>(settle))
        case "jumpTo":
            guard let a0 = args[0].tuple(2).flatMap({ v0 -> (Double, Double)? in
                guard let v0_0 = v0[0].f64, let v0_1 = v0[1].f64 else { return nil }
                return (v0_0, v0_1)
            }) else { return settle.reject("bad arguments — MapView.jumpTo: center") }
            let w1 = args[1]
            var a1: MapCameraMove? = nil
            if w1.isPresent {
                guard let v = MapCameraMove(wire: w1) else { return settle.reject("bad arguments — MapView.jumpTo: options") }
                a1 = v
            }
            plugin.jumpTo(a0, a1, Reply<Void, MapViewCode>(settle))
        case "fitPoints":
            guard let a0 = args[0].list({ v0 in
                v0.tuple(2).flatMap({ v1 -> (Double, Double)? in
                    guard let v1_0 = v1[0].f64, let v1_1 = v1[1].f64 else { return nil }
                    return (v1_0, v1_1)
                })
            }) else { return settle.reject("bad arguments — MapView.fitPoints: points") }
            let w1 = args[1]
            var a1: MapFitOptions? = nil
            if w1.isPresent {
                guard let v = MapFitOptions(wire: w1) else { return settle.reject("bad arguments — MapView.fitPoints: options") }
                a1 = v
            }
            plugin.fitPoints(a0, a1, Reply<Void, MapViewCode>(settle))
        case "setPadding":
            guard let a0 = MapPadding(wire: args[0]) else { return settle.reject("bad arguments — MapView.setPadding: padding") }
            plugin.setPadding(a0, Reply<Void, MapViewCode>(settle))
        case "getCamera":
            plugin.getCamera(Reply<MapCamera, MapViewCode>(settle) { v, w in v.write(to: w) })
        case "setUserLocation":
            let w0 = args[0]
            var a0: (Double, Double)? = nil
            if w0.isPresent {
                guard let v = w0.tuple(2).flatMap({ v0 -> (Double, Double)? in
                    guard let v0_0 = v0[0].f64, let v0_1 = v0[1].f64 else { return nil }
                    return (v0_0, v0_1)
                }) else { return settle.reject("bad arguments — MapView.setUserLocation: lngLat") }
                a0 = v
            }
            let w1 = args[1]
            var a1: MapUserLocationOptions? = nil
            if w1.isPresent {
                guard let v = MapUserLocationOptions(wire: w1) else { return settle.reject("bad arguments — MapView.setUserLocation: options") }
                a1 = v
            }
            plugin.setUserLocation(a0, a1, Reply<Void, MapViewCode>(settle))
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func destroy() { plugin.destroy() }
}
