// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// map: the view "map", contract version 1.

import Foundation
import UIKit
import LeCodes

// MARK: - The contract's types

public struct MapParams {
    /// A style URL the map fetches itself.
    public var style: String?
    /// A style as JSON text; wins over `style`. It has no base url: every url INSIDE it (sources,
    /// sprite, glyphs) must be absolute.
    public var styleJson: String?
    public var center: (Double, Double)?
    /// Default 12 with a center.
    public var zoom: Double?
    public var minZoom: Double?
    public var maxZoom: Double?
    /// Degrees clockwise from north.
    public var bearing: Double?
    /// Degrees from the vertical.
    public var pitch: Double?
    /// The two-finger rotate gesture. Default true.
    public var rotate: Bool?
    /// The two-finger tilt gesture. Default false.
    public var tilt: Bool?

    public init(style: String? = nil, styleJson: String? = nil, center: (Double, Double)? = nil, zoom: Double? = nil, minZoom: Double? = nil, maxZoom: Double? = nil, bearing: Double? = nil, pitch: Double? = nil, rotate: Bool? = nil, tilt: Bool? = nil) {
        self.style = style
        self.styleJson = styleJson
        self.center = center
        self.zoom = zoom
        self.minZoom = minZoom
        self.maxZoom = maxZoom
        self.bearing = bearing
        self.pitch = pitch
        self.rotate = rotate
        self.tilt = tilt
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["style"]) {
            guard let style = Wire.string(o["style"]) else { return nil }
            self.style = style
        } else { self.style = nil }
        if Wire.present(o["styleJson"]) {
            guard let styleJson = Wire.string(o["styleJson"]) else { return nil }
            self.styleJson = styleJson
        } else { self.styleJson = nil }
        if Wire.present(o["center"]) {
            guard let center = Wire.array(o["center"], 2).flatMap({ v0 -> (Double, Double)? in guard let v0_0 = Wire.f64(v0[0]), let v0_1 = Wire.f64(v0[1]) else { return nil }; return (v0_0, v0_1) }) else { return nil }
            self.center = center
        } else { self.center = nil }
        if Wire.present(o["zoom"]) {
            guard let zoom = Wire.f64(o["zoom"]) else { return nil }
            self.zoom = zoom
        } else { self.zoom = nil }
        if Wire.present(o["minZoom"]) {
            guard let minZoom = Wire.f64(o["minZoom"]) else { return nil }
            self.minZoom = minZoom
        } else { self.minZoom = nil }
        if Wire.present(o["maxZoom"]) {
            guard let maxZoom = Wire.f64(o["maxZoom"]) else { return nil }
            self.maxZoom = maxZoom
        } else { self.maxZoom = nil }
        if Wire.present(o["bearing"]) {
            guard let bearing = Wire.f64(o["bearing"]) else { return nil }
            self.bearing = bearing
        } else { self.bearing = nil }
        if Wire.present(o["pitch"]) {
            guard let pitch = Wire.f64(o["pitch"]) else { return nil }
            self.pitch = pitch
        } else { self.pitch = nil }
        if Wire.present(o["rotate"]) {
            guard let rotate = Wire.bool(o["rotate"]) else { return nil }
            self.rotate = rotate
        } else { self.rotate = nil }
        if Wire.present(o["tilt"]) {
            guard let tilt = Wire.bool(o["tilt"]) else { return nil }
            self.tilt = tilt
        } else { self.tilt = nil }
    }
}

public enum MapLayerKind: String {
    case markers
    case line

    init?(wire: Any?) {
        guard let raw = Wire.string(wire), let value = MapLayerKind(rawValue: raw) else { return nil }
        self = value
    }
}

/// The keys of both kinds; a half reads the ones of the kind it is asked for.
public struct MapLayerOptions {
    /// markers: group nearby markers (a cluster tap zooms in). Default false.
    public var cluster: Bool?
    /// markers: px. Default 50.
    public var clusterRadius: Double?
    /// markers: the zoom at which clusters stop forming.
    public var clusterMaxZoom: Double?
    /// line.
    public var color: String?
    /// line: px. Default 4.
    public var width: Double?
    /// line: 0–1. Default 1.
    public var opacity: Double?

    public init(cluster: Bool? = nil, clusterRadius: Double? = nil, clusterMaxZoom: Double? = nil, color: String? = nil, width: Double? = nil, opacity: Double? = nil) {
        self.cluster = cluster
        self.clusterRadius = clusterRadius
        self.clusterMaxZoom = clusterMaxZoom
        self.color = color
        self.width = width
        self.opacity = opacity
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["cluster"]) {
            guard let cluster = Wire.bool(o["cluster"]) else { return nil }
            self.cluster = cluster
        } else { self.cluster = nil }
        if Wire.present(o["clusterRadius"]) {
            guard let clusterRadius = Wire.f64(o["clusterRadius"]) else { return nil }
            self.clusterRadius = clusterRadius
        } else { self.clusterRadius = nil }
        if Wire.present(o["clusterMaxZoom"]) {
            guard let clusterMaxZoom = Wire.f64(o["clusterMaxZoom"]) else { return nil }
            self.clusterMaxZoom = clusterMaxZoom
        } else { self.clusterMaxZoom = nil }
        if Wire.present(o["color"]) {
            guard let color = Wire.string(o["color"]) else { return nil }
            self.color = color
        } else { self.color = nil }
        if Wire.present(o["width"]) {
            guard let width = Wire.f64(o["width"]) else { return nil }
            self.width = width
        } else { self.width = nil }
        if Wire.present(o["opacity"]) {
            guard let opacity = Wire.f64(o["opacity"]) else { return nil }
            self.opacity = opacity
        } else { self.opacity = nil }
    }
}

public struct MapCameraMove {
    public var zoom: Double?
    public var bearing: Double?
    public var pitch: Double?
    /// flyTo only: ms. Default 600.
    public var duration: Double?

    public init(zoom: Double? = nil, bearing: Double? = nil, pitch: Double? = nil, duration: Double? = nil) {
        self.zoom = zoom
        self.bearing = bearing
        self.pitch = pitch
        self.duration = duration
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["zoom"]) {
            guard let zoom = Wire.f64(o["zoom"]) else { return nil }
            self.zoom = zoom
        } else { self.zoom = nil }
        if Wire.present(o["bearing"]) {
            guard let bearing = Wire.f64(o["bearing"]) else { return nil }
            self.bearing = bearing
        } else { self.bearing = nil }
        if Wire.present(o["pitch"]) {
            guard let pitch = Wire.f64(o["pitch"]) else { return nil }
            self.pitch = pitch
        } else { self.pitch = nil }
        if Wire.present(o["duration"]) {
            guard let duration = Wire.f64(o["duration"]) else { return nil }
            self.duration = duration
        } else { self.duration = nil }
    }
}

/// Px, or a share of the view's size as "NN%".
public enum MapInset {
    case number(Double)
    case string(String)

    init?(wire: Any?) {
        if let v = Wire.f64(wire) { self = .number(v); return }
        if let v = Wire.string(wire) { self = .string(v); return }
        return nil
    }
}

public struct MapPadding {
    public var top: MapInset?
    public var left: MapInset?
    public var bottom: MapInset?
    public var right: MapInset?

    public init(top: MapInset? = nil, left: MapInset? = nil, bottom: MapInset? = nil, right: MapInset? = nil) {
        self.top = top
        self.left = left
        self.bottom = bottom
        self.right = right
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["top"]) {
            guard let top = MapInset(wire: o["top"]) else { return nil }
            self.top = top
        } else { self.top = nil }
        if Wire.present(o["left"]) {
            guard let left = MapInset(wire: o["left"]) else { return nil }
            self.left = left
        } else { self.left = nil }
        if Wire.present(o["bottom"]) {
            guard let bottom = MapInset(wire: o["bottom"]) else { return nil }
            self.bottom = bottom
        } else { self.bottom = nil }
        if Wire.present(o["right"]) {
            guard let right = MapInset(wire: o["right"]) else { return nil }
            self.right = right
        } else { self.right = nil }
    }
}

public enum MapFitOptionsPadding {
    case number(Double)
    case mapPadding(MapPadding)

    init?(wire: Any?) {
        if let v = Wire.f64(wire) { self = .number(v); return }
        if let v = MapPadding(wire: wire) { self = .mapPadding(v); return }
        return nil
    }
}

public struct MapFitOptions {
    /// Around the points: px on every edge, or per edge. Added to the view padding.
    public var padding: MapFitOptionsPadding?
    /// Default: 16 for one point, none otherwise.
    public var maxZoom: Double?
    /// Default true.
    public var animate: Bool?

    public init(padding: MapFitOptionsPadding? = nil, maxZoom: Double? = nil, animate: Bool? = nil) {
        self.padding = padding
        self.maxZoom = maxZoom
        self.animate = animate
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["padding"]) {
            guard let padding = MapFitOptionsPadding(wire: o["padding"]) else { return nil }
            self.padding = padding
        } else { self.padding = nil }
        if Wire.present(o["maxZoom"]) {
            guard let maxZoom = Wire.f64(o["maxZoom"]) else { return nil }
            self.maxZoom = maxZoom
        } else { self.maxZoom = nil }
        if Wire.present(o["animate"]) {
            guard let animate = Wire.bool(o["animate"]) else { return nil }
            self.animate = animate
        } else { self.animate = nil }
    }
}

public struct MapCamera {
    public var center: (Double, Double)
    public var zoom: Double
    public var bearing: Double
    public var pitch: Double

    public init(center: (Double, Double), zoom: Double, bearing: Double, pitch: Double) {
        self.center = center
        self.zoom = zoom
        self.bearing = bearing
        self.pitch = pitch
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["center"] = [Wire.number(center.0), Wire.number(center.1)] as [Any]
        o["zoom"] = Wire.number(zoom)
        o["bearing"] = Wire.number(bearing)
        o["pitch"] = Wire.number(pitch)
        return o
    }
}

public struct MapUserLocationOptions {
    /// Meters — the halo around the dot.
    public var accuracy: Double?
    /// Degrees clockwise from north — the direction wedge; null hides it.
    public var heading: Double?

    public init(accuracy: Double? = nil, heading: Double? = nil) {
        self.accuracy = accuracy
        self.heading = heading
    }

    init?(wire: Any?) {
        guard let o = Wire.object(wire) else { return nil }
        if Wire.present(o["accuracy"]) {
            guard let accuracy = Wire.f64(o["accuracy"]) else { return nil }
            self.accuracy = accuracy
        } else { self.accuracy = nil }
        if Wire.present(o["heading"]) {
            guard let heading = Wire.f64(o["heading"]) else { return nil }
            self.heading = heading
        } else { self.heading = nil }
    }
}

public enum MapFeatureId {
    case string(String)
    case number(Double)

    var wire: Any {
        switch self {
        case .string(let v): return v
        case .number(let v): return Wire.number(v)
        }
    }
}

/// A feature of a managed source under a tap.
public struct MapFeature {
    /// The source's name — the layer's name in the app.
    public var source: String
    public var id: MapFeatureId?
    public var properties: [String: Any]

    public init(source: String, id: MapFeatureId? = nil, properties: [String: Any]) {
        self.source = source
        self.id = id
        self.properties = properties
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["source"] = source
        if let v = id { o["id"] = v.wire } else { o["id"] = NSNull() }
        o["properties"] = properties.mapValues({ v0 -> Any in v0 })
        return o
    }
}

public struct MapTap {
    public var lngLat: (Double, Double)
    /// View-space point, logical px.
    public var point: (Double, Double)
    /// Absent for a tap that hit no feature of a managed source. A tap on a CLUSTER zooms in and
    /// sends no event.
    public var feature: MapFeature?

    public init(lngLat: (Double, Double), point: (Double, Double), feature: MapFeature? = nil) {
        self.lngLat = lngLat
        self.point = point
        self.feature = feature
    }

    var wire: Any {
        var o: [String: Any] = [:]
        o["lngLat"] = [Wire.number(lngLat.0), Wire.number(lngLat.1)] as [Any]
        o["point"] = [Wire.number(point.0), Wire.number(point.1)] as [Any]
        if let v = feature { o["feature"] = v.wire }
        return o
    }
}

// MARK: - MapView

/// The codes the calls of "map" reject with.
public enum MapViewCode: String, PluginCode {
    case notReady
    case noPoints
}

/// The events of "map": what the plugin sends the app. Any thread.
public struct MapViewEvents {
    let channel: NativeViewChannel

    /// The style loaded and the map takes calls. Fires again after every style reload.
    public func ready() { channel.emit("ready") }

    public func tap(_ payload: MapTap) { channel.emit("tap", payload.wire) }

    /// The camera settled after a gesture or an animation.
    public func moveEnd(_ payload: MapCamera) { channel.emit("moveEnd", payload.wire) }

    /// A problem that is never fatal: a style that would not load, a source out of reach.
    public func error(message: String) {
        var o: [String: Any] = [:]
        o["message"] = message
        channel.emit("error", o)
    }
}

/// The view "map".
/// What the plugin implements. A call arrives on the main thread; its reply is settled exactly
/// once, now or later, from any thread.
public protocol MapViewPlugin: AnyObject {
    /// The view the host mounts: fullscreen, or embedded among a screen's children.
    var view: UIView { get }

    /// Make sure the GeoJSON source `source` exists. A source the style declares is used as is (its
    /// layers draw, only data flows); otherwise the half creates it with the default layers of `kind`.
    /// Rejects with .notReady.
    func ensureLayer(_ source: String, _ kind: MapLayerKind, _ options: MapLayerOptions?, _ reply: Reply<Void, MapViewCode>)
    func removeLayer(_ source: String, _ reply: Reply<Void, MapViewCode>)
    /// Replace the data of a GeoJSON source: a Feature or a FeatureCollection.
    /// Rejects with .notReady.
    func setData(_ source: String, _ geojson: Any, _ reply: Reply<Void, MapViewCode>)
    func flyTo(_ center: (Double, Double), _ options: MapCameraMove?, _ reply: Reply<Void, MapViewCode>)
    func jumpTo(_ center: (Double, Double), _ options: MapCameraMove?, _ reply: Reply<Void, MapViewCode>)
    /// Fit the camera to the points.
    /// Rejects with .noPoints.
    func fitPoints(_ points: [(Double, Double)], _ options: MapFitOptions?, _ reply: Reply<Void, MapViewCode>)
    /// The part of the view covered by the app's UI; camera moves center inside the rest.
    func setPadding(_ padding: MapPadding, _ reply: Reply<Void, MapViewCode>)
    /// Rejects with .notReady.
    func getCamera(_ reply: Reply<MapCamera, MapViewCode>)
    /// Move the user puck; null hides it.
    func setUserLocation(_ lngLat: (Double, Double)?, _ options: MapUserLocationOptions?, _ reply: Reply<Void, MapViewCode>)

    /// The instance goes (the world swapped): release the hardware.
    func destroy()
}

public extension MapViewPlugin {
    func destroy() {}
}

public enum MapViewChannel {
    /// What the halves register under.
    public static let name = "map"
    /// The contract's version: the highest `@since` of its members.
    public static let version = 1

    /// Register the view: `make` builds one instance from its params.
    public static func register(in engine: LeCodesEngine, _ make: @escaping (MapParams, MapViewEvents) -> MapViewPlugin) {
        engine.registerView(name) { params, channel in
            MapViewGlue(make(MapParams(wire: params) ?? MapParams(), MapViewEvents(channel: channel)))
        }
    }
}

/// Reads a call off the wire and hands it to the plugin; a malformed call never reaches it.
final class MapViewGlue: NativeViewInstance {
    private let plugin: MapViewPlugin

    init(_ plugin: MapViewPlugin) { self.plugin = plugin }

    var view: UIView { plugin.view }

    func call(_ method: String, _ args: [Any], _ settle: ChannelSettle) {
        switch method {
        case "ensureLayer":
            guard let source = Wire.string((args.count > 0 ? args[0] : nil)) else { return settle.reject("bad arguments — MapView.ensureLayer: source") }
            guard let kind = MapLayerKind(wire: (args.count > 1 ? args[1] : nil)) else { return settle.reject("bad arguments — MapView.ensureLayer: kind") }
            let a2: Any? = args.count > 2 ? args[2] : nil
            var options: MapLayerOptions? = nil
            if Wire.present(a2) {
                guard let v = MapLayerOptions(wire: a2) else { return settle.reject("bad arguments — MapView.ensureLayer: options") }
                options = v
            }
            plugin.ensureLayer(source, kind, options, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "removeLayer":
            guard let source = Wire.string((args.count > 0 ? args[0] : nil)) else { return settle.reject("bad arguments — MapView.removeLayer: source") }
            plugin.removeLayer(source, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "setData":
            guard let source = Wire.string((args.count > 0 ? args[0] : nil)) else { return settle.reject("bad arguments — MapView.setData: source") }
            guard let geojson = Wire.json((args.count > 1 ? args[1] : nil)) else { return settle.reject("bad arguments — MapView.setData: geojson") }
            plugin.setData(source, geojson, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "flyTo":
            guard let center = Wire.array((args.count > 0 ? args[0] : nil), 2).flatMap({ v0 -> (Double, Double)? in guard let v0_0 = Wire.f64(v0[0]), let v0_1 = Wire.f64(v0[1]) else { return nil }; return (v0_0, v0_1) }) else { return settle.reject("bad arguments — MapView.flyTo: center") }
            let a1: Any? = args.count > 1 ? args[1] : nil
            var options: MapCameraMove? = nil
            if Wire.present(a1) {
                guard let v = MapCameraMove(wire: a1) else { return settle.reject("bad arguments — MapView.flyTo: options") }
                options = v
            }
            plugin.flyTo(center, options, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "jumpTo":
            guard let center = Wire.array((args.count > 0 ? args[0] : nil), 2).flatMap({ v0 -> (Double, Double)? in guard let v0_0 = Wire.f64(v0[0]), let v0_1 = Wire.f64(v0[1]) else { return nil }; return (v0_0, v0_1) }) else { return settle.reject("bad arguments — MapView.jumpTo: center") }
            let a1: Any? = args.count > 1 ? args[1] : nil
            var options: MapCameraMove? = nil
            if Wire.present(a1) {
                guard let v = MapCameraMove(wire: a1) else { return settle.reject("bad arguments — MapView.jumpTo: options") }
                options = v
            }
            plugin.jumpTo(center, options, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "fitPoints":
            guard let points = Wire.list((args.count > 0 ? args[0] : nil), { v0 in Wire.array(v0, 2).flatMap({ v1 -> (Double, Double)? in guard let v1_0 = Wire.f64(v1[0]), let v1_1 = Wire.f64(v1[1]) else { return nil }; return (v1_0, v1_1) }) }) else { return settle.reject("bad arguments — MapView.fitPoints: points") }
            let a1: Any? = args.count > 1 ? args[1] : nil
            var options: MapFitOptions? = nil
            if Wire.present(a1) {
                guard let v = MapFitOptions(wire: a1) else { return settle.reject("bad arguments — MapView.fitPoints: options") }
                options = v
            }
            plugin.fitPoints(points, options, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "setPadding":
            guard let padding = MapPadding(wire: (args.count > 0 ? args[0] : nil)) else { return settle.reject("bad arguments — MapView.setPadding: padding") }
            plugin.setPadding(padding, Reply<Void, MapViewCode>(settle) { _ in nil })
        case "getCamera":
            plugin.getCamera(Reply<MapCamera, MapViewCode>(settle) { v in v.wire })
        case "setUserLocation":
            let a0: Any? = args.count > 0 ? args[0] : nil
            var lngLat: (Double, Double)? = nil
            if Wire.present(a0) {
                guard let v = Wire.array(a0, 2).flatMap({ v0 -> (Double, Double)? in guard let v0_0 = Wire.f64(v0[0]), let v0_1 = Wire.f64(v0[1]) else { return nil }; return (v0_0, v0_1) }) else { return settle.reject("bad arguments — MapView.setUserLocation: lngLat") }
                lngLat = v
            }
            let a1: Any? = args.count > 1 ? args[1] : nil
            var options: MapUserLocationOptions? = nil
            if Wire.present(a1) {
                guard let v = MapUserLocationOptions(wire: a1) else { return settle.reject("bad arguments — MapView.setUserLocation: options") }
                options = v
            }
            plugin.setUserLocation(lngLat, options, Reply<Void, MapViewCode>(settle) { _ in nil })
        default:
            settle.reject("Unknown method: \(method)")
        }
    }

    func destroy() { plugin.destroy() }
}
