// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// qr-scanner: the view "qrScanner", contract version 1.

import { ViewChannel } from "lecodes-sdk/plugin"
import type { QRScannerEvents, QRScannerParams } from "../contract"

/** What the halves register under. */
export const NAME = "qrScanner"
/** The contract's version: the highest `@since` of its members. */
export const VERSION = 1

// ---- the element ----------------------------------------------------------------------------------

/** The view "qrScanner" with the wire's methods as its own. */
export class QRScannerBase extends ViewChannel<QRScannerEvents> {
  constructor(params: QRScannerParams = {}) { super("QRScanner", NAME, params) }
}
