// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// push: the service "push", contract version 1.

import { ServiceChannel } from "lecodes-sdk/plugin"
import type { PushEvents, PushParams, PushPayload, PushRegisterOptions, PushRegistration, PushStatus } from "../contract"

/** What the halves register under. */
export const NAME = "push"
/** The contract's version: the highest `@since` of its members. */
export const VERSION = 1

// ---- the wire, call by call ----------------------------------------------------------------------

/** Permission + registration state. Never prompts. */
export const getStatus = (service: ServiceChannel<PushEvents>): Promise<PushStatus> =>
  service._call("getStatus", [])

/** Ask for the permission (the first time) and register this device. Idempotent.
 *  Rejects with "denied" / "unavailable". */
export const register = (service: ServiceChannel<PushEvents>, options?: PushRegisterOptions): Promise<PushRegistration> =>
  service._call("register", [options])

/** Remove this device's registration.
 *  Rejects with "unavailable". */
export const unregister = (service: ServiceChannel<PushEvents>): Promise<void> =>
  service._call("unregister", [])

/** The notification that cold-started this world, or null. Stable across calls. */
export const getLaunch = (service: ServiceChannel<PushEvents>): Promise<PushPayload | null> =>
  service._call("getLaunch", [])

// ---- the client -----------------------------------------------------------------------------------

/** The service "push" with the wire's methods as its own. */
export class PushBase extends ServiceChannel<PushEvents> {
  constructor(params: PushParams = {}) { super("Push", NAME, params) }

  /** Permission + registration state. Never prompts. */
  getStatus(): Promise<PushStatus> { return getStatus(this) }
  /** Ask for the permission (the first time) and register this device. Idempotent.
   *  Rejects with "denied" / "unavailable". */
  register(options?: PushRegisterOptions): Promise<PushRegistration> { return register(this, options) }
  /** Remove this device's registration.
   *  Rejects with "unavailable". */
  unregister(): Promise<void> { return unregister(this) }
  /** The notification that cold-started this world, or null. Stable across calls. */
  getLaunch(): Promise<PushPayload | null> { return getLaunch(this) }
}
