// GENERATED by `lecodes plugin gen` from contract.d.ts — do not edit.
// camera: the view "camera", contract version 1.

import { ViewChannel, _toFile, type File } from "lecodes-sdk/plugin"
import type { CameraEvents, CameraParams, Facing } from "../contract"

/** What the halves register under. */
export const NAME = "camera"
/** The contract's version: the highest `@since` of its members. */
export const VERSION = 1

// ---- the wire, call by call ----------------------------------------------------------------------

/** Capture a still frame as a JPEG.
 *  Rejects with "failed". */
export const takePhoto = (view: ViewChannel<CameraEvents>): Promise<File> =>
  view._call("takePhoto", []).then((w: any) => _toFile(w))

/** Switch the camera while the preview is live. */
export const setFacingMode = (view: ViewChannel<CameraEvents>, mode: Facing): Promise<void> =>
  view._call("setFacingMode", [mode])

// ---- what the host's half has --------------------------------------------------------------------

/** A method of the contract. */
export type Method = "takePhoto" | "setFacingMode"

/** Whether this host has the view "camera" — and, given a method, a half new enough for it
 *  (a method added after the first version of the contract is tagged `@since`). */
export const supports = (method?: Method): boolean =>
  ViewChannel.supports(NAME)   // every method is of version 1

// ---- the element ----------------------------------------------------------------------------------

/** The view "camera" with the wire's methods as its own. */
export class CameraViewBase extends ViewChannel<CameraEvents> {
  constructor(params: CameraParams = {}) { super("CameraView", NAME, params) }

  /** Capture a still frame as a JPEG.
   *  Rejects with "failed". */
  takePhoto(): Promise<File> { return takePhoto(this) }
  /** Switch the camera while the preview is live. */
  setFacingMode(mode: Facing): Promise<void> { return setFacingMode(this, mode) }
}
